const SYS_URL = '/ip_service/interface/'
const SYS_URL1 = '/ip_sysm/interface/'
const SYS_URL2 = '/ip_import_data/interface/'
const SYS_URL3 = '/ip_automail/interface/'
const SYS_URL4 = '/ip_sec/interface/'
const SYS_URL5 = '/ip_kg/interface/'
const SYS_URL6 = '/ip_hrm/interface/'
const SYS_URL7 = '/ip_miga/interface/'
const SYS_URL8 = '/ip_knowledgeBase/interface/'
const URL_Tem = {
  queryKnowledgeBase: SYS_URL8 + 'knowledgebase/queryKnowledgeBase',
  // 委托办案
  queryAgentTask: SYS_URL + 'ipctask/queryAgentTask',
  queryRecentMeeting: SYS_URL + 'itinerary/queryRecentMeeting',
  // 商标审限
  queryAgencyInfoByCustId: SYS_URL + 'caseUtil/queryAgencyInfoByCustId',
  queryTrademarkHearTermList: SYS_URL + 'caseUtil/queryTrademarkHearTermList',
  queryTrademarkHearTermById: SYS_URL + 'caseUtil/queryTrademarkHearTermById',
  updateTrademarkHearTerm: SYS_URL + 'caseUtil/updateTrademarkHearTerm',
  addTrademarkHearTerm: SYS_URL + 'caseUtil/addTrademarkHearTerm',
  delTrademarkHearTermById: SYS_URL + 'caseUtil/delTrademarkHearTermById',
  //
  relevantCase:SYS_URL + 'caseInfo/relevantCase',
  queryCaseByagent:SYS_URL + 'caseInfo/queryCaseByagent',
  queryRelevantCase:SYS_URL + 'caseInfo/queryRelevantCase',
  queryWkgRole: SYS_URL1 + 'workgroup/queryWkgRole',
  translate:  SYS_URL + 'trademarkCase/translate',
  delCase:  SYS_URL + 'trademarkCase/delCase',
  addWaitCases: SYS_URL + 'task/addWaitCases',
  deleteWaitCase: SYS_URL + 'task/deleteWaitCase',
  preCaseApproval: SYS_URL + 'taskdo/preCaseApproval',
  queryCaseInfo:SYS_URL + 'trademarkCase/queryCaseInfo',
  batchHeigCredit:SYS_URL + 'taskdo/batchHeigCredit',
  transferDoc:SYS_URL + 'taskdo/transferDoc',//制作
  importCPCFile:SYS_URL + 'patentCPC/importCPCFile',//cpc导出
  queryUnloadedDocFromCPC:SYS_URL + 'patentCPC/queryUnloadedDocFromCPC',//cpc录入
  queryLawList:SYS_URL + 'taskdo/queryLawList',//法律条款列表
  preSubmit:SYS_URL + 'taskdo/submit',
  officialCase:SYS_URL + 'taskdo/officialCase',
  passOrReturn:SYS_URL + 'taskdo/passOrReturn',
  checkCases:SYS_URL + 'taskdo/checkCases',
  queryDocByDraftNumber:SYS_URL + 'task/queryDocByDraftNumber',
  zipDoc: SYS_URL + 'task/zipDoc',
  queryMaterialByCaseId: SYS_URL + 'material/queryMaterialByCaseId',
  creatematerial:`${window.location.origin}/ip_service/interface/material/creatematerial`,
  delCaseMaterial:SYS_URL + 'material/delCaseMaterial',
  queryMaterialType:SYS_URL + 'material/queryMaterialType',
  creatematerial1:`${window.location.origin}/ip_service/interface/material/creatematerial`,
  submitOffical: SYS_URL + 'taskdo/submitOffical',
  createSubmitOfficials: SYS_URL + "submitOfficial/createSubmitOfficials",
  queryUserAll: SYS_URL1 + 'util/queryUserAll',
  queryInstruction:SYS_URL+'taskdo/queryInstruction',
  submitOfficalAudit:SYS_URL+'taskdo/submitOfficalAudit',
  typeInOfficalDoc: SYS_URL+'taskdo/typeInOfficalDoc',
  queryMailingType: SYS_URL+'task/queryMailingType',
  auditOfficalDoc: SYS_URL+'taskdo/auditOfficalDoc',
  queryDocs: SYS_URL + 'taskdo/queryDocs',
  getOfficialInformList: SYS_URL + 'officialInform/getOfficialInformList',
  updateZczStatus: SYS_URL + 'officialInform/updateZczStatus',
  queryCase: SYS_URL + 'taskdo/queryCase',
  modifyOfficalDoc: SYS_URL + 'taskdo/modifyOfficalDoc',
  queryAppByCusetId: SYS_URL1 + 'agencycontact/queryAppByCusetId',
  queryCanProcessTm: SYS_URL + 'trademark/queryCanProcessTm',
  queryAppAddrByTm: SYS_URL1 + 'agencycontact/queryAppAddrByTm',
  importTmRegNumberData: SYS_URL2 + 'tmdata/importTmRegNumberData',
  getSubmitOfficialList: SYS_URL + 'submitOfficial/getSubmitOfficialList',
  submitOfficalModify: SYS_URL + 'taskdo/submitOfficalModify',
  queryMailList: SYS_URL + 'mail/queryMailList',
  queryJieduan: SYS_URL + 'mail/queryJieduan',
  queryJieduanOfMailType: SYS_URL3 + 'mail/queryJieduanOfMailType',
  queryMailTypeAll: SYS_URL + 'mail/queryMailTypeAll',
  queryMailType: SYS_URL + 'mail/queryMailType',
  sendMail: SYS_URL + 'mail/sendMail',
  upMailbox: SYS_URL1 + 'mailbox/upMailbox',
  addMailbox: SYS_URL1 + 'mailbox/addMailbox',
  upPassword: SYS_URL1 + 'user/upPassword',
  getUser: SYS_URL1 + 'user/getUser',
  upUser: SYS_URL1 + 'user/upUser',
  switchoverAccount: SYS_URL4 + 'auth/switchoverAccount',
  tmdetail: SYS_URL + 'trademark/tmdetail',
  queryAgencyName: SYS_URL + 'trademarkCase/queryAgencyName',
  deleteIns: SYS_URL + 'task/deleteIns',
  deleteDoc: SYS_URL + 'task/deleteDoc',
  deleteCase: SYS_URL + 'task/deleteCase',
  getChangeCaseList: SYS_URL + 'trademarkCase/getChangeCaseList',
  create2: SYS_URL + 'task/create2',
  querymaterialbyapp: SYS_URL + 'material/querymaterialbyapp',
  modifyMaterialStatus: SYS_URL + 'material/modifyMaterialStatus',
  decFile: SYS_URL + 'material/decFile',
  deleteFile: SYS_URL + 'material/deleteFile',
  queryDefaultUser: SYS_URL + 'material/queryDefaultUser',
  copyMaterial: SYS_URL + 'material/copyMaterial',
  creatematerialsimple: SYS_URL + 'material/creatematerialsimple',
  queryShuomingshu: SYS_URL + 'material/queryShuomingshu',
  queryMaterialBySort: SYS_URL + 'material/queryMaterialBySort',
  queryMaterialList: SYS_URL + 'material/queryMaterialList',
  viewPdf: SYS_URL + 'material/viewPdf',
  viewMsg: SYS_URL + 'material/viewMsg',
  querySortList: SYS_URL + 'material/querySortList',
  putMaterialIntoRubbish: SYS_URL + 'material/putMaterialIntoRubbish',
  restoreMaterial: SYS_URL + 'material/restoreMaterial',
  deleteCaseMaterial: SYS_URL + 'material/deleteCaseMaterial',
  downloadMaterial: SYS_URL + 'material/downloadMaterial',
  getTimelimitList: SYS_URL + 'timelimit/getTimelimitList',
  getTimelimitObj: SYS_URL + 'timelimit/getTimelimitObj',
  getCaption: SYS_URL + 'timelimit/getCaption',
  queryWithdraw: SYS_URL + 'caseUtil/queryWithdraw',
  queryIndustryTag: SYS_URL + 'caseUtil/queryIndustryTag',
  queryHehuoren: SYS_URL + 'caseUtil/queryHehuoren',
  queryCaseMaterial: SYS_URL + 'material/queryCaseMaterial',
  getTimelimitTypeAll: SYS_URL + 'timelimitType/getTimelimitTypeAll',
  getWriteoffState: SYS_URL + 'timelimitType/getWriteoffState',
  queryMaterialDocType: SYS_URL + 'material/queryMaterialDocType',
  queryMaterialTypeByDocId: SYS_URL + 'material/queryMaterialTypeByDocId',
  getCase: SYS_URL + 'timelimit/getCase',
  delTimelimit: SYS_URL + 'timelimit/delTimelimit',
  upTimelimit: SYS_URL + 'timelimit/upTimelimit',
  getCaseTimelimitList: SYS_URL + 'timelimit/getCaseTimelimitList',
  getTimelimitByCaseId: SYS_URL + 'timelimit/getTimelimitByCaseId',
  addTimelimit: SYS_URL + 'timelimit/addTimelimit',
  getTimelimitDetail: SYS_URL + 'timelimit/getTimelimit',
  getTimelimitType: SYS_URL + 'timelimitType/getTimelimitType',
  getAbslimitDate: SYS_URL + 'timelimitType/getAbslimitDate',
  queryMaterialById: SYS_URL + 'material/queryMaterialById',
  updateMaterial: SYS_URL + 'material/updateMaterial',
  getTimelimitListByTltId: SYS_URL + 'timelimit/getTimelimitListByTltId',
  getCaseStage: SYS_URL + 'timelimitType/getCaseStage',
  getCaseStageBytimeTypeWriteoffState: SYS_URL + 'timelimitType/getCaseStageBytimeTypeWriteoffState',
  getTimelimitWriteoff:SYS_URL + 'timelimitDispose/getTimelimitWriteoff',
  addTimelimitWriteoff:SYS_URL + 'timelimitDispose/addTimelimitWriteoff',
  auditTimelimit:SYS_URL + 'timelimitDispose/auditTimelimit',
  queryCaseByMaterialId:SYS_URL + 'material/queryCaseByMaterialId',
  getBusinessList: SYS_URL + 'business/getBusinessList',
  queryCustGroupByCaseId: SYS_URL + 'caseInfo/queryCustGroupByCaseId',

  //商标检测
  queryTmTarget: SYS_URL + 'tmMonitor/queryTmTarget',
  queryTmEdition: SYS_URL + 'tmMonitor/queryTmEdition',
  importTmMonitorData: SYS_URL2 + 'tmdata/importTmMonitorData',
  tmAnnouncement: SYS_URL2 + 'tmdata/tmAnnouncement',
  queryTmAnnouncement: SYS_URL + 'tmMonitor/queryTmAnnouncement',
  queryTmRecordType: SYS_URL + 'tmMonitor/queryTmRecordType',

  getWorkDateList: SYS_URL + 'caseUtil/getWorkDateList',
  updateWorkDate: SYS_URL + 'caseUtil/updateWorkDate',
  insertWorkDate: SYS_URL + 'caseUtil/insertWorkDate',
  delWorkDate: SYS_URL + 'caseUtil/delWorkDate',

  modifyjoinapp: SYS_URL + 'trademarkCaseJoinApp/modifyjoinapp',
  sendBusiness: SYS_URL + 'business/sendBusiness',
  getRemindRecord: SYS_URL + 'business/getRemindRecord',
  getRemindType: SYS_URL + 'remind/getRemindType',
  upRemindType: SYS_URL + 'remind/upRemindType',
  getPlan: SYS_URL + 'remind/getPlan',
  getSum: SYS_URL + 'caseUtil/getSum',
  getBusinessNum: SYS_URL + 'caseUtil/getBusinessNum',
  getTimelimitNum: SYS_URL + 'caseUtil/getTimelimitNum',
  taskQueryAll: SYS_URL + 'caseUtil/queryAll',
  sumQueryMailList: SYS_URL + 'caseUtil/queryMailList',
  queryBilltaskNum: SYS_URL + 'caseUtil/queryBillTaskNum',
  getManualRecognitionOfficialInfoCount: SYS_URL + 'officialInform/getManualRecognitionOfficialInfoCount',
  recognizedError: SYS_URL + 'officialInform/recognizedError',
  getManualRecognitionOfficialInfoList: SYS_URL + 'officialInform/getManualRecognitionOfficialInfoList',
  queryTrademarkCaseByOfficialDoc: SYS_URL + 'officialInform/queryTrademarkCaseByOfficialDoc',
  manualBindOfficialDocAndCase: SYS_URL + 'officialInform/manualBindOfficialDocAndCase',
  modifyOfficalDocBatch: SYS_URL + 'officialInform/modifyOfficalDocBatch',
  lowCreditAudit: SYS_URL + 'taskdo/lowCreditAudit',
  queryBillTask: SYS_URL + 'Bill/queryBillTask',
  batchdoBillTask: SYS_URL + 'Bill/batchdoBillTask',
  queryBudgetFee: SYS_URL + 'budget/queryBudgetFee',
  queryBudgetLog: SYS_URL + 'budget/queryBudgetLog',
  queryBudgetAndFeeDetail: SYS_URL + 'budget/queryBudgetAndFeeDetail',
  queryBudget: SYS_URL + 'budget/queryBudget',
  createBudget: SYS_URL + 'budget/createBudget',
  saveBudget: SYS_URL + 'budget/saveBudget',
  addBudget: SYS_URL + 'budget/addBudget',
  createBudgetConfig: SYS_URL + 'budget/createBudgetConfig',
  queryChangedBudget: SYS_URL + 'budget/queryChangedBudget',
  getCaseByTmFileId: SYS_URL +'officialInform/getCaseByTmFileId',
  queryBudgetList: SYS_URL +'budget/queryBudgetList',
  queryDepartMent: SYS_URL +'budget/queryDepartMent',
  queryBudgetByFeetId: SYS_URL+ 'budget/queryBudgetByFeetId',
  queryFeeType: SYS_URL+'budget/queryFeeType',
  submitBudget: SYS_URL + 'budget/submitBudget',
  queryBudgetDetailSum: SYS_URL + 'budget/queryBudgetDetailSum',
  modifyMaterialType: SYS_URL + 'material/modifyMaterialType',
  queryBudgetConfig: SYS_URL +'budget/queryBudgetConfig',
  queryBudgetForAjust: SYS_URL +'budget/queryBudgetForAjust',
  queryBudgetFeeType: SYS_URL +'budget/queryBudgetFeeType',
  ajustBudget: SYS_URL +'budget/ajustBudget',
  queryOperator: SYS_URL +'budget/queryOperator',
  updateBudgetConfig: SYS_URL + 'budget/updateBudgetConfig',
  deleteBudgetConfig: SYS_URL + 'budget/deleteBudgetConfig',
  auditBudget: SYS_URL + 'budget/auditBudget',
  queryTaskUser: SYS_URL + 'budget/queryTaskUser',
  queryAppUser: SYS_URL + 'budget/queryAppUser',
  deleteBudget: SYS_URL + 'budget/deleteBudget',
  createGovList: SYS_URL + 'form/createGovList',
  createForm: SYS_URL + 'form/createForm',
  createAbroadBillTemplate: SYS_URL + 'form/createAbroadBillTemplate',
  queryHerderList: SYS_URL + 'caseUtil/queryHerderList',
  deriveList: SYS_URL + 'caseUtil/deriveList',
  querySimilarCustomer: SYS_URL + 'caseUtil/querySimilarCustomer',
  queryMandate: SYS_URL + 'form/queryMandate',
  createPOA: SYS_URL + 'form/createPOA',
  queryAllMailType: SYS_URL3 + 'mail/queryAllMailType',
  createMailByself: SYS_URL3 + 'mail/createMailByself',
  queryListOfMaterial: SYS_URL + 'form/queryListOfMaterial',
  createListOfMaterial: SYS_URL + 'form/createListOfMaterial',
  queryCorrelationCaseList:SYS_URL + 'trademarkCase/queryCorrelationCaseList',
  queryPatentMailType: SYS_URL + 'mail/queryPatentMailType',
  queryMailTypeByJieduan: SYS_URL3 + 'mail/queryMailTypeByJieduan',
  createMultSubmitMaterial:SYS_URL + 'material/createMultSubmitMaterial',
  createMultMaterial:SYS_URL + 'material/createMultMaterial',
  updateFeeDetailList:SYS_URL +'fee/updateFeeDetailList',
  checkLawsuitReceiptNo:SYS_URL +'fee/checkLawsuitReceiptNo',
  queryFeeList:SYS_URL +'fee/queryFeeList',
  getInvoiceBorrowInfo:SYS_URL +'fee/getInvoiceBorrowInfo',
  createFee: SYS_URL +'fee/createFee',
  queryFeeTask: SYS_URL +'fee/queryFeeTask',
  remainingBudget:SYS_URL +'budget/remainingBudget',
  queryReport:SYS_URL +'budget/queryReport',
  queryFeeTypeList:SYS_URL +'fee/queryFeeTypeList',
  queryFeeInfo:SYS_URL +'fee/queryFeeInfo',
  queryCompanyByPermission:SYS_URL +'fee/queryCompanyByPermission',
  queryCompany:SYS_URL +'fee/queryCompany',
  updateFeeBatch:SYS_URL +'fee/updateFeeBatch',
  unbindWorkHour:SYS_URL +'fee/unbindWorkHour',
  bindWorkHour:SYS_URL +'fee/bindWorkHour',
  queryWorkHourList:SYS_URL +'fee/queryWorkHourList',
  copyFee:SYS_URL +'fee/copyFee',
  queryPayMode:SYS_URL +'fee/queryPayMode',
  submitFee:SYS_URL +'fee/submitFee',
  updateFee:SYS_URL +'fee/updateFee',
  batchDoFeeTask:SYS_URL +'fee/batchDoFeeTask',
  createFeeInCase:SYS_URL +'fee/createFeeInCase',
  queryWorkByUserId:SYS_URL1+'user/queryWorkByUserId',
  noCase: SYS_URL +'officialInform/noCase',
  deleteFeeDetail:SYS_URL +'fee/deleteFeeDetail',
  deleteFee:SYS_URL +'fee/deleteFee',
  assignCase:SYS_URL +'taskdo/assignCase',
  queryFeeWfstatus: SYS_URL + 'fee/queryFeeWfstatus',
  endorseFee: SYS_URL + 'fee/endorseFee',
  checkFeeTasker: SYS_URL +'fee/checkFeeTasker',
  queryEndorseTasker: SYS_URL + 'fee/queryEndorseTasker',
  assginTaskCandidate: SYS_URL + 'process/assginTaskCandidate',
  queryTackBackTask: SYS_URL + 'process/queryTackBackTask',
  queryAssignTask:SYS_URL + 'process/queryAssignTask',
  tackBackTask: SYS_URL + 'process/tackBackTask',
  createReceipt: SYS_URL + 'form/createReceipt',
  queryBillReceipt: SYS_URL + 'receipt/queryBillReceipt',
  createReceiptTemplate: SYS_URL + 'receipt/createReceiptTemplate',
  manualFinish: SYS_URL + 'mail/manualFinish',
  batchFinish: SYS_URL + 'mail/batchFinish',
  queryReceiptIitem: SYS_URL +'receipt/queryReceiptIitem',
  updateReceiptBatch: SYS_URL +'receipt/updateReceiptBatch',
  queryReceiptList: SYS_URL +'receipt/queryReceiptList',
  queryReceiptCompany: SYS_URL +'receipt/queryReceiptCompany',
  queryBankaccountListBycustId: SYS_URL1 + 'customerBankaccount/queryBankaccountListBycustId',
  updateMail: SYS_URL +'mail/updateMail',
  getFilterScheme: SYS_URL +'caseUtil/getFilterScheme',
  addFilterScheme: SYS_URL +'caseUtil/addFilterScheme',
  delFilterScheme: SYS_URL +'caseUtil/delFilterScheme',
  getTmDate: SYS_URL + 'officialInform/getTmDate',
  queryFeeTaskDefine: SYS_URL + 'fee/queryFeeTaskDefine',
  querySpecificPayType: SYS_URL + 'fee/querySpecificPayType',
  saveReceipt: SYS_URL + 'receipt/saveReceipt',
  queryReceiptDetail: SYS_URL + 'receipt/queryReceiptDetail',
  queryApplicantByIdList:SYS_URL1 + 'agencycontact/queryApplicantByIdList',
  getAdversaryArray:SYS_URL + 'caseUtil/getAdversaryArray',
  submitReceipt:SYS_URL + 'receipt/submitReceipt',
  deleteReceipt:SYS_URL + 'receipt/deleteReceipt',
  feeGetCase:SYS_URL + 'fee/getCase',
  getDocNumber:SYS_URL + 'autoParsing/getDocNumber',
  upWorkMember:SYS_URL + 'caseUtil/upWorkMember',
  getCaseWorkgroupChangeMessage:SYS_URL + 'caseUtil/getCaseWorkgroupChangeMessage',
  upCaseWorkgroupChangeMessage:SYS_URL + 'caseUtil/upCaseWorkgroupChangeMessage',
  queryKeyName: SYS_URL + 'task/queryKeyName',
  queryFeeSum: SYS_URL + 'fee/queryFeeSum',
  receiptCreateReceipt:SYS_URL + 'receipt/createReceipt',
  receiptToTask:SYS_URL + 'receipt/doTask',
  changeCaseStage:SYS_URL + 'task/changeCaseStage',
  queryCaseProgress:SYS_URL + 'trademarkCase/queryCaseProgress',
  checkPermission:SYS_URL +'taskdo/checkPermission',
  queryAuditUserList:SYS_URL +'caseUtil/queryAuditUserList',
  queryCaseFeeInfo: SYS_URL +'fee/queryCaseFeeInfo',
  queryServerIp: SYS_URL1 +'auth/queryServerIp',
  revocationTimelimitWriteoff: SYS_URL+'timelimitDispose/revocationTimelimitWriteoff',
  saveLog: SYS_URL + 'log/saveLog',
  batchModifyAbroadBill:SYS_URL + 'abroadbill/batchModifyAbroadBill',
  queryCaseAbroadBillInfo:SYS_URL + 'abroadbill/queryCaseAbroadBillInfo',
  queryAbroadList:SYS_URL + 'abroadbill/queryAbroadList',
  copyAbroadBill:SYS_URL + 'abroadbill/copyAbroadBill',
  getAbroadBill:SYS_URL + 'abroadbill/getAbroadBill',
  createAbroadBill:SYS_URL + 'abroadbill/createAbroadBill',
  saveAbroadBill:SYS_URL + 'abroadbill/saveAbroadBill',
  submitAbroadBill:SYS_URL + 'abroadbill/submitAbroadBill',
  queryAbroadBillDetail:SYS_URL + 'abroadbill/queryAbroadBillDetail',
  getCaseList:SYS_URL + 'abroadbill/getCaseList',
  deleteAbroadBill:SYS_URL + 'abroadbill/deleteAbroadBill',
  batchPayAbroadBill:SYS_URL + 'abroadbill/batchPayAbroadBill',
  createAbroadBillFee:SYS_URL + 'abroadbill/createFee',
  queryCaseMaterialList: SYS_URL + 'trademarkCase/queryCaseMaterialList',
  copyCase: SYS_URL + 'task/copyCase',
  queryTrademarkCaseOfficial: SYS_URL +'officialInform/queryTrademarkCaseOfficial',
  doAbroadBillTask:SYS_URL + 'abroadbill/doAbroadBillTask',
  uploadDocFile: SYS_URL + 'material/uploadDocFile',
  updateBillRecordListByBillRecordIds: SYS_URL + 'billRecord/updateBillRecordListByBillRecordIds',
  queryBillRecordListByBillRecordIds: SYS_URL + 'billRecord/queryBillRecordListByBillRecordIds',
  billRecordDelete: SYS_URL + 'billRecord/delete',
  queryBillInfoByBillId: SYS_URL + 'Bill/queryBillInfoByBillId',
  deleteBillInfo: SYS_URL + '/Bill/deleteBillInfo',
  addActivityFile: SYS_URL1 + '/activity/addActivityFile',
  delActivityFile: SYS_URL1 + '/activity/delActivityFile',
  queryBillTaskRecord: SYS_URL + 'Bill/queryBillTaskRecord',
  downloadMaterialBatch: SYS_URL + 'Bill/downloadMaterialBatch',
  queryTaskDefine: SYS_URL + 'process/queryTaskDefine',
  getCaseInfo: SYS_URL + 'caseInfo/getCaseInfo',
  modifyCaseType: SYS_URL + 'caseInfo/modifyCaseType',
  modifyCaseStage: SYS_URL + 'caseInfo/modifyCaseStage',
  queryCaseProgressName: SYS_URL + 'caseUtil/queryCaseProgressName',
  getCaseHistory: SYS_URL + 'caseInfo/getCase',
  getCaseTime:  SYS_URL + 'caseInfo/getCaseTime',
  disposeAgentNum: SYS_URL + 'caseUtil/disposeAgentNum',
  billDiscount:SYS_URL+'caseUtil/billDiscount',
  queryUserByRoleId:SYS_URL1+'user/queryUserByRoleId',
  insertSystemUpdateRecord: SYS_URL1+'systemUpdateRecord/insertSystemUpdateRecord',
  deleteSystemUpdateRecord: SYS_URL1+'systemUpdateRecord/deleteSystemUpdateRecord',
  updateSystemUpdateRecord: SYS_URL1+'systemUpdateRecord/updateSystemUpdateRecord',
  querySystemUpdateRecord: SYS_URL1+'systemUpdateRecord/querySystemUpdateRecord',
  querySystemUpdateRecordList: SYS_URL1+'systemUpdateRecord/querySystemUpdateRecordList',
  updateUserPassWordByUsername:SYS_URL1+'user/updateUserPassWordByUsername',
  queryLogList:'124/ipdoc/logs/front.log',
  qyeryTasks:"zyHq/queryTasks",
  excelMould:SYS_URL+'caseUtil/excelMould',
  getApprovalNumber:SYS_URL+'caseUtil/getApprovalNumber',
  getPropertyList:SYS_URL+'caseUtil/getPropertyList',
  getSubmitDate:SYS_URL+'caseUtil/getSubmitDate',
  queryFilter:SYS_URL5+'docUtil/queryFilter',
  queryPropertyList:SYS_URL5+'docUtil/queryPropertyList',
  queryDoc:SYS_URL5+'docUtil/queryDoc',
  queryDocList:SYS_URL5+'docUtil/queryDocList',
  queryDocStructure: SYS_URL5+'docUtil/queryDocStructure',
  queryDocDetail: SYS_URL5+'docUtil/queryDocDetail',
  queryDocBystId:SYS_URL5+'docUtil/queryDocBystId',
  updateWkg:SYS_URL+'caseUtil/updateWkg',
  queryCustomerSource: SYS_URL1 + 'util/queryCustomerSource',
  queryCaseTypeList: SYS_URL5+'docUtil/queryCaseTypeList',
  queryPageData:SYS_URL5+'docUtil/queryPageData',
  queryFilterConfig:SYS_URL5+'docUtil/queryFilterConfig',
  configFilter:SYS_URL5+'docUtil/configFilter',
  queryCaseWork:SYS_URL+'trademarkCase/queryCaseWork',
  queryNavigation:SYS_URL5+'rule/queryNavigation',
  queryKnowledgeProperty:SYS_URL5+'rule/queryKnowledgeProperty',
  updateKnowledgeProperty:SYS_URL5+'rule/updateKnowledgeProperty',
  queryRuleByindex:SYS_URL5+'rule/queryRuleByindex',
  queryRuleByRuleName:SYS_URL5+'rule/queryRuleByRuleName',
  queryProperty:SYS_URL5+'rule/queryProperty',
  insertRule: SYS_URL5+'rule/insertRule',
  updateRule: SYS_URL5+'rule/updateRule',
  deleteRule: SYS_URL5+'rule/deleteRule',
  analysisWord: SYS_URL5+'essay/analysisWord',
  queryContents: SYS_URL5+'essay/queryContents',
  uploadBatchFile: SYS_URL+'material/uploadBatchFile',
  queryContentsDelTitle: SYS_URL5 + 'essay/queryContentsDelTitle',
  analysisWordOne: SYS_URL5 + 'essay/analysisWordOne',
  queryFileByTltId: SYS_URL + 'material/queryFileByTltId',
  queryUpdateDate:SYS_URL5+'docUtil/queryUpdateDate',
  queryTongJiGOutline:SYS_URL5+'docUtil/queryTongJiGOutline',
  addBillRecord:SYS_URL+'billRecord/addBillRecord',
  updateDocCensus:SYS_URL5+'rule/updateDocCensus',
  addComment:SYS_URL5+'docComment/addComment',
  queryCdResult:SYS_URL5+'docUtil/queryCdResult',
  queryTmFirstCheck:  SYS_URL + 'tmMonitor/queryTmFirstCheck',
  queryTmFirstCheckByDsId:  SYS_URL + 'tmMonitor/queryTmFirstCheckByDsId',
  checkRule:SYS_URL5+'rule/checkRule',
  queryKbLibList:SYS_URL+'kbmg/queryKbLibList',
  queryUserLibList:SYS_URL+'kbmg/queryUserLibList',
  queryKbLibUser:SYS_URL+'kbmg/queryKbLibUser',
  updateUserLib:SYS_URL+'kbmg/updateUserLib',
  tmFirstCheck:SYS_URL2 + 'tmdata/tmFirstCheck',
  queryUsersTaskList:SYS_URL+ 'pm/queryUsersTaskList',
  queryTotalHour:SYS_URL+ 'pm/queryTotalHour',
  queryRemindPlan:SYS_URL+ 'remindPlan/queryRemindPlan',
  getRemindPlan:SYS_URL+ 'remindPlan/getRemindPlan',
  addRemindPlan:SYS_URL+ 'remindPlan/addRemindPlan',
  modifyRemindPlan:SYS_URL+ 'remindPlan/modifyRemindPlan',
  deleteRemindPlan:SYS_URL+ 'remindPlan/deleteRemindPlan',
  importTemplateData:SYS_URL2 + 'tmdata/importTemplateData',
  queryList:SYS_URL5 + 'pinyin/queryList',
  BillInternalQueryToDoTask :SYS_URL +'BillInternal/queryToDoTask',
  updateTmFirstCheckInfo :SYS_URL+'tmMonitor/updateTmFirstCheckInfo',
  deleteTmFirstCheckInfo :SYS_URL+'tmMonitor/deleteTmFirstCheckInfo',
  addTmFirstCheckInfo :SYS_URL+'tmMonitor/addTmFirstCheckInfo',
  deleteMaterialById :SYS_URL+'material/deleteMaterialById',
  queryDeptGroup:SYS_URL+'caseUtil/queryDeptGroup',
  createProject:SYS_URL+ 'pm/createProject',
  queryProjectList:SYS_URL+ 'pm/queryProjectList',
  queryRecentProject:SYS_URL+ 'pm/queryRecentProject',
  queryProjectDetail:SYS_URL+ 'pm/queryProjectDetail',
  modifyProject:SYS_URL+ 'pm/modifyProject',
  deleteProject:SYS_URL+ 'pm/deleteProject',
  queryTaskById:SYS_URL+ 'pm/queryTaskById',
  queryProjectFeeInfo: SYS_URL+ 'fee/queryProjectFeeInfo',
  createFeeInProject: SYS_URL+ 'fee/createFeeInProject',
  modifyRemindPlanPm: SYS_URL+ 'pm/modifyRemindPlan',
  finishTask: SYS_URL+ 'pm/finishTask',
  addTaskWach: SYS_URL+ 'pm/addTaskWach',
  deleteTaskWach:SYS_URL+ 'pm/deleteTaskWach',
  queryTaskWatch:SYS_URL+ 'pm/queryTaskWatch',
  queryTaskMemo:SYS_URL+ 'pm/queryTaskMemo',
  deleteTaskMemo:SYS_URL+ 'pm/deleteTaskMemo',
  modifyTaskMemo:SYS_URL+ 'pm/modifyTaskMemo',
  addTaskMemo:SYS_URL+ 'pm/addTaskMemo',
  taskFinishTask:SYS_URL+ 'task/finishTask',
  createFeeTemplate:SYS_URL+ 'form/createFeeTemplate',
  getRemindRecordDetail:SYS_URL+ 'business/getRemindRecordDetail',

  queryMaterialByObjTypeAndInstId: SYS_URL+ 'material/queryMaterialByObjTypeAndInstId',

  // 取证模板导出
  protectionCaseTemplateGeneration: SYS_URL + 'form/protectionCaseTemplateGeneration',
  downloadEvidenceMaterialzipPackage: SYS_URL + 'form/downloadEvidenceMaterialzipPackage',

  // 入账外借发票
  queryInvoiceBorrowList:SYS_URL + 'invoiceBorrow/queryInvoiceBorrowList',
  createInvoiceBorrow:SYS_URL + 'invoiceBorrow/createInvoiceBorrow',
  modifyInvoiceBorrow:SYS_URL + 'invoiceBorrow/modifyInvoiceBorrow',
  doInvoiceBorrowTask:SYS_URL + 'invoiceBorrow/doInvoiceBorrowTask',
  deleteInvoiceBorrow:SYS_URL + 'invoiceBorrow/deleteInvoiceBorrow',
  checkInvoiceBorrowTasker:SYS_URL + 'invoiceBorrow/checkTasker',
  endorseInvoiceBorrow:SYS_URL + 'invoiceBorrow/endorse',
  modifyInvoiceBorrowBatch:SYS_URL + 'invoiceBorrow/modifyInvoiceBorrowBatch',
  returnInvoice:SYS_URL + 'invoiceBorrow/returnInvoice',

  // 发票库
  queryInvoiceLibrary:SYS_URL + 'invoice/queryInvoice',
  createInvoice:SYS_URL + 'invoice/createInvoice',
  uploadInvoice:SYS_URL + 'invoice/uploadInvoice',
  modifyInvoice:SYS_URL + 'invoice/modifyInvoice',
  batchProcess:SYS_URL + 'invoice/batchProcess',
  deleteInvoice:SYS_URL + 'invoice/deleteInvoice',
  modifyInvoiceStatus:SYS_URL + 'invoice/modifyInvoiceStatus',
  modifyVeriCode:SYS_URL + 'invoice/modifyVeriCode',
  batchModifyInvoice:SYS_URL + 'invoice/batchModifyInvoice',
  checkInvoice:SYS_URL + 'invoice/checkInvoice',

  // 借款管理
  queryLoanList:SYS_URL + 'loan/queryLoanList',
  createLoan:SYS_URL + 'loan/createLoan',
  deleteLoan:SYS_URL + 'loan/deleteLoan',
  modifyLoan:SYS_URL + 'loan/modifyLoan',
  checkBorrowTasker:SYS_URL + 'loan/checkTasker',
  endorseBorrow:SYS_URL + 'loan/endorse',
  doLoanTask:SYS_URL + 'loan/doLoanTask',

  // 报表中心
  queryReportCompany: SYS_URL + 'financial/queryCompany',
  queryReportCompany1: SYS_URL + 'company/queryCompany',
  queryReportCompanySelect: SYS_URL + 'financial/queryCompany',
  financeReportUploadFile: SYS_URL + 'financial/uploadFile',
  queryDeptCompany: SYS_URL + 'company/queryDeptCompany',
  createOrModifyCompany: SYS_URL + 'company/createOrModifyCompany',
  deleteReportCompany: SYS_URL + 'financial/deleteCompany',
  queryFinancialDoc: SYS_URL + 'financial/queryDoc',
  deleteFinancialDoc: SYS_URL + 'financial/deleteDoc',
  // 报表-财务状况
  queryFinancialList: SYS_URL + 'financial/queryFinancialList',
  createFinancial: SYS_URL + 'financial/createFinancial',
  modifyFinancial: SYS_URL + 'financial/modifyFinancial',
  deleteFinancial: SYS_URL + 'financial/deleteFinancial',
  queryFinancialLocked: SYS_URL + 'financial/queryLocked',
  modifyFinancialLocked: SYS_URL + 'financial/modifyLocked',
  financialCreateExcel: SYS_URL + 'financial/createExcel',
  // 报表-从业人员工资总额
  queryfSalaryList: SYS_URL + 'salary/queryfSalaryList',
  createFSalary: SYS_URL + 'salary/createFSalary',
  modifyfSalary: SYS_URL + 'salary/modifyfSalary',
  salaryCreateExcel: SYS_URL + 'salary/createExcel',
  deletefSalary: SYS_URL + 'salary/deletefSalary',
  querySalaryLocked: SYS_URL + 'salary/queryLocked',
  modifySalaryLocked: SYS_URL + 'salary/modifyLocked',

  // 报表-经营财务研发
  queryFManageDevList: SYS_URL + 'manageDev/queryFManageDevList',
  createFManageDev: SYS_URL + 'manageDev/createFManageDev',
  modifyFManageDev: SYS_URL + 'manageDev/modifyFManageDev',
  manageDevCreateExcel: SYS_URL + 'manageDev/createExcel',
  deleteFManageDev: SYS_URL + 'manageDev/deleteFManageDev',
  queryManageDevLocked: SYS_URL + 'manageDev/queryLocked',
  modifyManageDevLocked: SYS_URL + 'manageDev/modifyLocked',
  // 报表-损益表
  queryFProfitLossList: SYS_URL + 'profitLoss/queryFProfitLossList',
  createFProfitLoss: SYS_URL + 'profitLoss/createFProfitLoss',
  modifyFProfitLoss: SYS_URL + 'profitLoss/modifyFProfitLoss',
  profitLossCreateExcel: SYS_URL + 'profitLoss/createExcel',
  deleteFProfitLoss: SYS_URL + 'profitLoss/deleteFProfitLoss',
  queryProfitLossLocked: SYS_URL + 'profitLoss/queryLocked',
  modifyProfitLossLocked: SYS_URL + 'profitLoss/modifyLocked',
  // 报表-资产负债表
  queryFAssetsDebtList: SYS_URL + 'assetsDebt/queryFAssetsDebtList',
  createFAssetsDebt: SYS_URL + 'assetsDebt/createFAssetsDebt',
  modifyFAssetsDebt: SYS_URL + 'assetsDebt/modifyFAssetsDebt',
  assetsDebtCreateExcel: SYS_URL + 'assetsDebt/createExcel',
  deleteFAssetsDebt: SYS_URL + 'assetsDebt/deleteFAssetsDebt',
  queryAssetsDebtLocked: SYS_URL + 'assetsDebt/queryLocked',
  modifyAssetsDebtLocked: SYS_URL + 'assetsDebt/modifyLocked',
  // 报表-资产情况表
  queryFFundBalanceList: SYS_URL + 'fundBalance/queryFFundBalanceList',
  createFFundBalance: SYS_URL + 'fundBalance/createFFundBalance',
  modifyFFundBalance: SYS_URL + 'fundBalance/modifyFFundBalance',
  fundBalanceCreateExcel: SYS_URL + 'fundBalance/createExcel',
  deleteFFundBalance: SYS_URL + 'fundBalance/deleteFFundBalance',
  queryFundBalanceLocked: SYS_URL + 'fundBalance/queryLocked',
  modifyFundBalanceLocked: SYS_URL + 'fundBalance/modifyLocked',
  queryFFundRegions: SYS_URL + 'fundBalance/queryFFundRegions',
  queryFFundAccountList: SYS_URL + 'fundBalance/queryFFundAccountList',
  createFFundRegions: SYS_URL + 'fundBalance/createFFundRegions',
  modifyFFundRegions: SYS_URL + 'fundBalance/modifyFFundRegions',
  createFFundBalanceBatch: SYS_URL + 'fundBalance/createFFundBalanceBatch',
  modifyFFundBalanceBatch: SYS_URL + 'fundBalance/modifyFFundBalanceBatch',
  deleteFFundRegions: SYS_URL + 'fundBalance/deleteFFundRegions',
  queryLastMonthFFundRegionsDetail: SYS_URL + 'fundBalance/queryLastMonthFFundRegionsDetail',
  createFFundAccount: SYS_URL + 'fundBalance/createFFundAccount',
  modifyFFundAccount: SYS_URL + 'fundBalance/modifyFFundAccount',
  deleteFFundAccount: SYS_URL + 'fundBalance/deleteFFundAccount',
  fundBalanceUploadImage: SYS_URL + 'fundBalance/uploadImage',

  // 人才库
  queryTalentPersonList: SYS_URL6 + 'talent/queryTalentPersonList',
  queryTalentPersonListNoPermission: SYS_URL6 + 'talent/queryTalentPersonListNoPermission',
  queryPositions: SYS_URL6 + 'talent/queryPositions',
  queryPersonAll: SYS_URL6 + 'talent/queryPersonAll',
  queryOrganizations: SYS_URL6 + 'talent/queryOrganizations',
  queryOrganizationsChild: SYS_URL6 + 'talent/queryOrganizationsChild',
  queryAttendanceArchivePage: '/ip_attendance/api/attendance/archive/page',
  queryAttendanceArchiveDetail: '/ip_attendance/api/attendance/archive/detail',
  createAttendanceArchive: '/ip_attendance/api/attendance/archive/create',
  updateAttendanceArchive: '/ip_attendance/api/attendance/archive/update',
  deleteAttendanceArchive: '/ip_attendance/api/attendance/archive/delete',
  changeAttendanceArchiveStatus: '/ip_attendance/api/attendance/archive/change-status',
  queryUnarchivedAttendanceArchivePage: '/ip_attendance/api/attendance/archive/unarchived/page',
  batchAssignAttendanceArchive: '/ip_attendance/api/attendance/archive/batch-assign',
  batchCreateAttendanceArchiveByDefault: '/ip_attendance/api/attendance/archive/batch-create-by-default',
  queryAttendanceArchiveHistoryPage: '/ip_attendance/api/attendance/archive/history/page',
  queryModifyRecords: SYS_URL6 + 'talent/queryModifyRecords',
  uploadPersonMaterial: SYS_URL6 + 'talent/uploadPersonMaterial',
  deletePersonMaterial: SYS_URL6 + 'talent/deletePersonMaterial',
  auditModifyRecord: SYS_URL6 + 'talent/auditModifyRecord',
  upsertPersonBasicInfoFromExcel: SYS_URL6 + 'talent/upsertPersonBasicInfoFromExcel',
  upsertPersonOtherInfoFromZip: SYS_URL6 + 'talent/upsertPersonOtherInfoFromZip',
  queryUnAuditModifyRecordNum: SYS_URL6 + 'talent/queryUnAuditModifyRecordNum',
  upsertPersonLaborContractFromExcel: SYS_URL6 + 'talent/upsertPersonLaborContractFromExcel',
  queryPersonPerformanceTemp: SYS_URL6 + 'talent/queryPersonPerformanceTemp',
  upsertPersonPerformance: SYS_URL6 + 'talent/upsertPersonPerformance',
  upsertPersonPerformanceTemp: SYS_URL6 + 'talent/upsertPersonPerformanceTemp',
  exportTalentPersonPerformance: SYS_URL6 + 'talent/exportTalentPersonPerformance',
  queryPersonPerformanceCompare: SYS_URL6 + 'talent/queryPersonPerformanceCompare',

  queryPositionAll: SYS_URL6 + 'talent/queryPositionAll',
  queryTalentPersonInfo: SYS_URL6 + 'talent/queryTalentPersonInfo',
  talentCreatematerialUrl: SYS_URL6 + 'talent/uploadMaterial',
  upsertDepartmentFromExcel: SYS_URL6 + 'talent/upsertDepartmentFromExcel',
  upsertTalentPersonFromExcel: SYS_URL6 + 'talent/upsertTalentPersonFromExcel',
  delectTalentMaterial: SYS_URL6 + 'talent/deleteMaterial',
  upsertTalentPersonInfo: SYS_URL6 + 'talent/upsertTalentPersonInfo',
  uploadCertificateMaterial: SYS_URL6 + 'talent/uploadCertificateMaterial',
  uploadEvaluateMaterialUrl: SYS_URL6 + 'talent/uploadEvaluateMaterial',
  deleteEvaluateMaterial: SYS_URL6 + 'talent/deleteEvaluateMaterial',
  queryPermissionAll: SYS_URL6 + 'talent/queryPermissionAll',
  queryPersonPermissions: SYS_URL6 + 'talent/queryPersonPermissions',
  updatePersonPermission: SYS_URL6 + 'talent/updatePersonPermission',
  updatePersonDeptPermission: SYS_URL6 + 'talent/updatePersonDeptPermission',
  exportPersonListToExcel: SYS_URL6 + 'talent/exportPersonListToExcel',
  statisticsTalentPersonAll: SYS_URL6 + 'talent/statisticsTalentPersonAll',
  statisticsTalentPersonByBusiness: SYS_URL6 + 'talent/statisticsTalentPersonByBusiness',
  statisticsNewTalentPerson: SYS_URL6 + 'talent/statisticsNewTalentPerson',
  statisticsTalentPersonForPatent: SYS_URL6 + 'talent/statisticsTalentPersonForPatent',
  statisticsQuitTalentPerson: SYS_URL6 + 'talent/statisticsQuitTalentPerson',
  statisticsQuitTalentPersonByBusiness: SYS_URL6 + 'talent/statisticsQuitTalentPersonByBusiness',
  talentClearCache: SYS_URL6 + 'talent/clearCache',
  updatePersonSummary: SYS_URL6 + 'talent/updatePersonSummary',
  exportPersonInfoListToExcel: SYS_URL6 + 'talent/exportPersonInfoListToExcel',
  queryPersonApproveTypes: SYS_URL + 'talent/queryPersonApproveTypes',
  queryPersonApproveList: SYS_URL + 'talent/queryPersonApproveList',
  queryApproveProcess: SYS_URL + 'talent/queryApproveProcess',
  createApproveProcess: SYS_URL + 'talent/createApproveProcess',
  saveApproveProcess: SYS_URL + 'talent/saveApproveProcess',
  deletePersonApprove: SYS_URL + 'talent/deletePersonApprove',
  revokeApproveProcess: SYS_URL + 'talent/revokeApproveProcess',
  queryApproveTaskRecord: SYS_URL + 'talent/queryApproveTaskRecord',
  auditPersonApprove: SYS_URL + 'talent/auditPersonApprove',
  countersignPersonApprove: SYS_URL + 'talent/countersignPersonApprove',

  // 薪酬统计
  upsertPersonBonusFromExcel: SYS_URL7 + 'talent/upsertPersonBonusFromExcel',
  upPersonSalaryFromExcel: SYS_URL7 + 'talent/upPersonSalaryFromExcel',
  upsertWinningBonusFromExcel: SYS_URL7 + 'talent/upsertWinningBonusFromExcel',
  upsertYearBonusFromExcel: SYS_URL7 + 'talent/upsertYearBonusFromExcel',
  uploadPartnerBonus: SYS_URL7 + 'talent/uploadPartnerBonus',
  uploadBeizhu: SYS_URL7 + 'talent/uploadBeizhu',
  queryTalentPersonSalaryInfo: SYS_URL7 + 'talent/queryTalentPersonSalaryInfo',
  updateTalentPersonSalaryInfo: SYS_URL7 + 'talent/updateTalentPersonSalaryInfo',
  deleteTalentPersonSalaryInfo: SYS_URL7 + 'talent/deleteTalentPersonSalaryInfo',
  querySalaryTongji: SYS_URL7 + 'talent/querySalaryTongji',
  salaryTongjiDeriveList: SYS_URL7 + 'talent/deriveList',
  queryTalentWinningBonusInfo: SYS_URL7 + 'talent/queryTalentWinningBonusInfo',
  updateTalentWinningBonusInfo: SYS_URL7 + 'talent/updateTalentWinningBonusInfo',
  deleteTalentWinningBonusInfo: SYS_URL7 + 'talent/deleteTalentWinningBonusInfo',
  queryTalentBonusInfo: SYS_URL7 + 'talent/queryTalentBonusInfo',
  updateTalentBonusInfo: SYS_URL7 + 'talent/updateTalentBonusInfo',
  deleteTalentBonusInfo: SYS_URL7 + 'talent/deleteTalentBonusInfo',
  createPersonBonus: SYS_URL7 + 'talent/createPersonBonus',
  queryTalentPersonExtInfo: SYS_URL7 + 'talent/queryTalentPersonExtInfo',
  updateTalentPersonExtInfo: SYS_URL7 + 'talent/updateTalentPersonExtInfo',
  deleteTalentPersonExtInfo: SYS_URL7 + 'talent/deleteTalentPersonExtInfo',
  queryPartnerBonusInfo: SYS_URL7 + 'talent/queryPartnerBonusInfo',
  updatePartnerBonusInfo: SYS_URL7 + 'talent/updatePartnerBonusInfo',
  deletePartnerBonusInfo: SYS_URL7 + 'talent/deletePartnerBonusInfo',
  queryAccountCustList: SYS_URL1 + `ipcCustomer/queryAccountCustList`,
  authorizeIPS: SYS_URL1 + `ipcCustomer/authorizeIPS`,

  //悬浮菜单
  queryMenuFabConfigByUserId: SYS_URL1 + `menu/queryMenuFabConfigByUserId`,
  saveMenuFabConfig: SYS_URL1 + `menu/saveMenuFabConfig`
}
module.exports = URL_Tem
