// const SYS_URL = '/pmtt_sysm/interface/'

// const {modifyBillBalanceBatch, modifyBillBatch} = require("@/api/billApi");
const SYS_URL = '/ip_sysm/interface/'
const SYS_URL5 = '/ip_sec/interface/'
const SYS_URL1 = '/ip_service/interface/'
const SYS_URL2 = '/ip_data/interface/'
const SYS_URL3 = '/ip_tmsearch/interface/'
const SYS_URL4 = '/ip_stats/interface/'
const SYS_URL6 = '/ip_dashboard/interface/'
const SYS_URL7 = '/ip_sysm_statistics/interface/'
const SYS_URL8 = '/ip_operatelog/interface/'
const SYS_URL9 = '/ip_document_search/interface/'
const SYS_URL10 = '/ip_contract/interface/'
const SYS_URL11 = '/ip_project/interface/'

const URL_Tem = {
  // 合同管理
  copyCreateContract: SYS_URL10 + 'contract/copyCreateContract', // 复制合同
  exportContractFlow: SYS_URL10 + 'contract/exportContractFlow', // 导出合同流程
  queryContractFeeInfo: SYS_URL1 + 'fee/queryContractFeeInfo',
  queryMyTaskList: SYS_URL1 + 'myTask/queryMyTaskList',
  getContractList: SYS_URL10 + 'contract/getList',
  getToBeReviewedNumber: SYS_URL10 + 'contract/getToBeReviewedNumber',
  saveContract: SYS_URL10 + 'contract/save',
  queryContractTypeList: SYS_URL10 + 'contract/queryContractTypeList',
  uploadAttachments:`${window.location.origin}/ip_contract/interface/contract/attachments/upload`,
  getContractDetail: SYS_URL10 + 'contract/getDetail',
  getCustomerList: SYS_URL10 + 'contract/getCustomerList',
  deleteContract: SYS_URL10 + 'contract/delete',
  auditContract: SYS_URL10 + 'contract/audit',
  queryTaskHandlers: SYS_URL10 + 'contract/queryTaskHandlers',
  queryContractTemplates: SYS_URL10 + 'contract/queryContractTemplates',
  queryCompany: SYS_URL10 + 'contract/queryCompany',
  getCaseCustomerManager: SYS_URL10 + 'contract/getCaseCustomerManager',
  getContractsByAgentNum: SYS_URL10 + 'contract/getContractsByAgentNum',
  contractViewPdf: SYS_URL10 + 'contract/viewPdf',
  // 文书检索
  updateFavoriteByUserId: SYS_URL9 + 'documentSearch/updateFavoriteByUserId',
  queryDocumentSearch: SYS_URL9 + 'documentSearch/queryDocumentSearch',
  queryDocumentSearchById: SYS_URL9 + 'documentSearch/queryDocumentSearchById',
  // 历史汇率
  checkUserPassWord: SYS_URL + 'user/checkUserPassWord',
  getQrCodeImage: SYS_URL1 + 'weixin/getQrCodeImage',
  queryCurrencyHistoryList: SYS_URL1 + 'caseUtil/queryCurrencyHistoryList',
  queryCurrencyHistoryById: SYS_URL1 + 'caseUtil/queryCurrencyHistoryById',
  updateCurrencyHistory: SYS_URL1 + 'caseUtil/updateCurrencyHistory',
  addCurrencyHistory: SYS_URL1 + 'caseUtil/addCurrencyHistory',
  delCurrencyHistoryById: SYS_URL1 + 'caseUtil/delCurrencyHistoryById',
  // 客户操作记录
  getLogInfo: SYS_URL8 + 'log/getLogInfo',
  // 商标监控
  queryMonitorResultSum: SYS_URL1 + 'monitorResult/queryMonitorResultSum',
  downloadSdResultExcel: SYS_URL1 + 'monitorResult/downloadSdResultExcel',
  queryAnnouncementName: SYS_URL1 + 'monitorResult/queryAnnouncementName',
  queryoAnnouncement: SYS_URL1 + 'monitorResult/queryoAnnouncement',
  queryMonitorResultList: SYS_URL1 + 'monitorResult/queryMonitorResultList',
  queryMonitorResult: SYS_URL1 + 'monitorResult/queryMonitorResult',
  downloadMonitorListExcel: SYS_URL1 + 'monitorResult/downloadMonitorListExcel',
  downloadMonitorResultExcel: SYS_URL1 + 'monitorResult/downloadMonitorResultExcel',
  queryoObjectHasResult: SYS_URL1 + 'monitorResult/queryoObjectHasResult',
  queryMonitorResultMessage: SYS_URL1 + 'monitorResult/queryMonitorResultMessage',
  queryMonitorFactorImage: SYS_URL1 + 'monitor/queryMonitorFactorImage',
  queryMonitorCustomer: SYS_URL1 + 'monitor/queryMonitorCustomer',
  batchState: SYS_URL1 + 'monitor/batchState',
  updatebatchStop: SYS_URL1 + 'monitor/updatebatchStop',
  queryIssueList: SYS_URL1 + 'monitor/queryIssueList',
  addMonitor: SYS_URL1 + 'monitor/addMonitor',
  delMonitor: SYS_URL1 + 'monitor/delMonitor',
  updateMonitor: SYS_URL1 + 'monitor/updateMonitor',
  queryMonitor: SYS_URL1 + 'monitor/queryMonitor',
  queryMonitorFactorType: SYS_URL1 + 'monitor/queryMonitorFactorType',
  queryMonitorList: SYS_URL1 + 'monitor/queryMonitorList',
  // 日程管理
  queryItineraryList: SYS_URL1 + 'itinerary/queryItineraryList',
  createItinerary: SYS_URL1 + 'itinerary/createItinerary',
  queryItineraryDetail: SYS_URL1 + 'itinerary/queryItineraryDetail',
  modifyItinerary: SYS_URL1 + 'itinerary/modifyItinerary',
  deleteItinerary: SYS_URL1 + 'itinerary/deleteItinerary',
  configItineraryUser: SYS_URL1 + 'itinerary/configItineraryUser',
  queryItineraryUser: SYS_URL1 + 'itinerary/queryItineraryUser',
  queryMeetingList: SYS_URL1 + 'itinerary/queryMeetingList',
  createMeeting: SYS_URL1 + 'itinerary/createMeeting',
  modifyMeeting: SYS_URL1 + 'itinerary/modifyMeeting',
  deleteMeeting: SYS_URL1 + 'itinerary/deleteMeeting',
  sendItineraryForOutlook: SYS_URL1 + 'itinerary/sendItineraryForOutlook',
  queryItineraryConfigUser: SYS_URL1 + 'itinerary/queryItineraryConfigUser',
  queryDefaultMeetingwxList: SYS_URL1 + 'itinerary/queryDefaultMeetingwxList',
  saveMeetingwx: SYS_URL1 + 'itinerary/saveMeetingwx',
  queryMeetingwxList: SYS_URL1 + 'itinerary/queryMeetingwxList',
  queryDeptGroupUser: SYS_URL1 + 'caseUtil/queryDeptGroupUser',
  queryTimeZone: SYS_URL1 + 'caseUtil/queryTimeZone',
  importItineraryData: SYS_URL1 + 'tmdata/importItineraryData',

  // 客户管理
  getBusinessUser: SYS_URL + 'user/getBusinessUser',
  queryCustomerPinpai: SYS_URL + 'customerPinpai/queryCustomerPinpai',
  saveCustomerPinpai: SYS_URL + 'customerPinpai/saveCustomerPinpai',
  addCustomerPinpai: SYS_URL + 'customerPinpai/addCustomerPinpai',
  updateCustomerPinpai: SYS_URL + 'customerPinpai/updateCustomerPinpai',
  delCustomerPinpai: SYS_URL + 'customerPinpai/delCustomerPinpai',
  updateCasePinpai: SYS_URL + 'customerPinpai/updateCasePinpai',
  updateCustomerFenzhiLianxiById: SYS_URL + 'customerFenzhiLianxi/updateCustomerFenzhiLianxiById',
  delCustomerFenzhiLianxi: SYS_URL + 'customerFenzhiLianxi/delCustomerFenzhiLianxi',
  addCustomerFenzhiLianxi: SYS_URL + 'customerFenzhiLianxi/addCustomerFenzhiLianxi',
  queryCustomerFenzhiLianxiByCustfzId: SYS_URL + 'customerFenzhiLianxi/queryCustomerFenzhiLianxiByCustfzId',
  stopCustomerContact: SYS_URL + 'customerContact/stopCustomerContact',
  getInfoData: SYS_URL7 + 'dashboard/getInfoData',
  queryFilterConfigUrl: SYS_URL7 + 'config/queryConfigFilter',
  delCustomerStatisticsPanelConfig: SYS_URL7 + 'config/delCustomerStatisticsPanelConfig',
  configFilterUrl: SYS_URL7 + 'config/configFilter',
  getPropertyPreferenceUrl: SYS_URL7 + 'config/getPropertyPreference',
  addCustomerStatisticsPanelConfig: SYS_URL7 + 'config/addCustomerStatisticsPanelConfig',
  getAllPanelsUrl: SYS_URL7 + 'config/getAllPanels',
  hideShowUserPanelUrl: SYS_URL7 + 'config/hideShowUserPanel',
  queryFilterUrl: SYS_URL7 + 'config/queryFilter',
  queryPanelTab: SYS_URL7 + 'config/queryPanelTab',
  getAllgraph: SYS_URL7 + 'config/getAllgraph',
  queryCustomerStatisticsPanel: SYS_URL7 + 'config/queryCustomerStatisticsPanel',
  getChartDataUrl: SYS_URL7 + 'dashboard/getChartData',
  queryCustomerJituanList: SYS_URL + 'customerJituan/queryCustomerJituanList',
  addCustomerJituan: SYS_URL + 'customerJituan/addCustomerJituan',
  queryCustomerJituanById: SYS_URL + 'customerJituan/queryCustomerJituanById',
  delCustomerJituan: SYS_URL + 'customerJituan/delCustomerJituan',
  updateCustomerJituanById: SYS_URL + 'customerJituan/updateCustomerJituanById',
  updateFenpeiForResponsible: SYS_URL + 'customerFenpei/updateFenpeiForResponsible',
  delFenpeiForResponsible: SYS_URL + 'customerFenpei/delFenpeiForResponsible',
  queryCustomerFenpeiVersion: SYS_URL + 'customerFenpei/queryCustomerFenpeiVersion',
  queryResponsibleVersion: SYS_URL + 'customerFenpei/queryResponsibleVersion',
  queryCustomerFenpeiRecord: SYS_URL + 'customerFenpei/queryCustomerFenpeiRecord',
  queryFenpeiRecordForResponsible: SYS_URL + 'customerFenpei/queryFenpeiRecordForResponsible',
  queryDetailByUserId: SYS_URL + 'customerFenpei/queryDetailByUserId',
  queryTongjiForResponsible: SYS_URL + 'customerFenpei/queryTongjiForResponsible',
  addFenpeiForResponsible: SYS_URL + 'customerFenpei/addFenpeiForResponsible',
  queryFenpeiForResponsible: SYS_URL + 'customerFenpei/queryFenpeiForResponsible',
  saveFenpeiForResponsible: SYS_URL + 'customerFenpei/saveFenpeiForResponsible',
  updateCustomerFenpeiById: SYS_URL + 'customerFenpei/updateCustomerFenpeiById',
  queryPerformanceDetailByWkgId: SYS_URL + 'customerFenpei/queryPerformanceDetailByWkgId',
  queryPerformanceByWkgId: SYS_URL + 'customerFenpei/queryPerformanceByWkgId',
  delCustomerFenpei: SYS_URL + 'customerFenpei/delCustomerFenpei',
  addCustomerFenpei: SYS_URL + 'customerFenpei/addCustomerFenpei',
  saveCustomerFenpei: SYS_URL + 'customerFenpei/saveCustomerFenpei',
  queryDomainList: SYS_URL + 'customerFenpei/queryDomainList',
  queryResopnseDomainList: SYS_URL + 'customerFenpei/queryResopnseDomainList',
  queryCustomerFenpei: SYS_URL + 'customerFenpei/queryCustomerFenpei',
  queryBillGroupbyCaseType: SYS_URL + 'customerYeji/queryBillGroupbyCaseType',
  queryBillGroupbyDomain: SYS_URL + 'customerYeji/queryBillGroupbyDomain',
  queryBillAndCase: SYS_URL + 'customerYeji/queryBillAndCase',
  queryTotalBillAndCase: SYS_URL + 'customerYeji/queryTotalBillAndCase',
  queryPerformanceDetailByUserId: SYS_URL + 'userPerformance/queryPerformanceDetailByUserId',
  queryUserPerformance: SYS_URL + 'userPerformance/queryUserPerformance',
  saveCustomerFenzhi: SYS_URL + 'customerFenzhi/saveCustomerFenzhi',
  updateCustomerFenzhiById: SYS_URL + 'customerFenzhi/updateCustomerFenzhiById',
  delCustomerFenzhi: SYS_URL + 'customerFenzhi/delCustomerFenzhi',
  queryCustomerFenzhiById: SYS_URL + 'customerFenzhi/queryCustomerFenzhiById',
  addCustomerFenzhi: SYS_URL + 'customerFenzhi/addCustomerFenzhi',
  mergeCustomer: SYS_URL + 'customer/mergeCustomer',
  queryCustInfo: SYS_URL + 'customer/queryCustInfo',
  queryCustomerFenzhiByCustId: SYS_URL + 'customerFenzhi/queryCustomerFenzhiByCustId',
  updateCustomerJiagouById: SYS_URL + 'customerJiagou/updateCustomerJiagouById',
  delCustomerJiagou: SYS_URL + 'customerJiagou/delCustomerJiagou',
  queryCustomerJiagouById: SYS_URL + 'customerJiagou/queryCustomerJiagouById',
  addCustomerJiagou: SYS_URL + 'customerJiagou/addCustomerJiagou',
  queryCustomerYuceByCustId: SYS_URL + 'customerYuce/queryCustomerYuceByCustId',
  addCustomerYuce: SYS_URL + 'customerYuce/addCustomerYuce',
  updateCustomerYuceByCustId: SYS_URL + 'customerYuce/updateCustomerYuceByCustId',
  queryCustomerYuceById: SYS_URL + 'customerYuce/queryCustomerYuceById',
  updateCustomerYuceById: SYS_URL + 'customerYuce/updateCustomerYuceById',
  saveCustomerYuce: SYS_URL + 'customerYuce/saveCustomerYuce',
  delCustomerYuce: SYS_URL + 'customerYuce/delCustomerYuce',
  // 商机列表
  queryShangjiList: SYS_URL + 'Shangji/queryShangjiList',
  addShangji: SYS_URL + 'Shangji/addShangji',
  queryShangji: SYS_URL + 'Shangji/queryShangji',
  updateShangji: SYS_URL + 'Shangji/updateShangji',
  delShangji: SYS_URL + 'Shangji/delShangji',
  shangjiFenpei: SYS_URL + 'Shangji/shangjiFenpei',
  // 撰写流程
  queryArticleWriter: SYS_URL1 + 'caseUtil/queryArticleWriter',
  queryZxLevel: SYS_URL1 + 'caseUtil/queryZxLevel',
  updateCaseCust: SYS_URL1 + 'trademarkCase/updateCaseCust',
  queryGoodsContrast: SYS_URL1 + 'trademarkCase/queryGoodsContrast',
  updateCaseCustInfo: SYS_URL1 + 'trademarkCase/updateCaseCustInfo',
  queryZxCaseCount: SYS_URL1 + 'trademarkCase/queryZxCaseCount',
  // 商品查对
  uploadImageAndReadGoods: SYS_URL1 + 'trademarkCase/uploadImageAndReadGoods',
  queryImageGoodsList: SYS_URL1 + 'trademarkCase/queryImageGoodsList',
  queryImageGoodsContrast: SYS_URL1 + 'trademarkCase/queryImageGoodsContrast',
  queryArticleDetail: SYS_URL1 + 'trademarkCase/queryArticleDetail',
  queryArticleList: SYS_URL1 + 'trademarkCase/queryArticleList',
  queryRefCaseIdList: SYS_URL1 + 'trademarkCase/queryRefCaseIdList',
  endorseArticleCaseTasker: SYS_URL1 + 'taskdo/endorseArticleCaseTasker',
  createArticleApp: SYS_URL1 + 'taskdo/createArticleApp',
  deleteArticleApp: SYS_URL1 + 'taskdo/deleteArticleApp',
  doArticleTask: SYS_URL1 + 'taskdo/doArticleTask',
  modifyArticleApp: SYS_URL1 + 'taskdo/modifyArticleApp',
  // 费用加批
  createFeeRule: SYS_URL1 + 'feeAddRules/create',
  modifyFeeRule: SYS_URL1 + 'feeAddRules/modify',
  deleteFeeRule: SYS_URL1 + 'feeAddRules/delete',
  queryFeeRuleList: SYS_URL1 + 'feeAddRules/queryList',
  // 对账
  queryCustContactEmailByCustId: SYS_URL + 'customerContact/queryCustContactEmailByCustId',
  createDunningSetting: SYS_URL + 'customer/createDunningSetting',
  deleteDunning: SYS_URL1 + 'dunning/deleteDunning',
  modifyDunning: SYS_URL1 + 'dunning/modifyDunning',
  queryDunningList: SYS_URL1 + 'dunning/queryDunningList',
  createDunning: SYS_URL1 + 'dunning/createDunning',
  deleteteLevel: SYS_URL + 'customer/deleteteLevel',
  modifyLevel: SYS_URL + 'customer/modifyLevel',
  updateLevel: SYS_URL + 'customer/updateLevel',
  queryLevel: SYS_URL + 'customer/queryLevel',
  deleteDMemo: SYS_URL + 'customer/deleteDMemo',
  modifyDMemo: SYS_URL + 'customer/modifyDMemo',
  createDMemo: SYS_URL + 'customer/createDMemo',
  queryDMemo: SYS_URL + 'customer/queryDMemo',
  queryTemplate: SYS_URL1 + 'dunning/queryTemplate',
  queryDebtCustomer: SYS_URL1 + 'dunning/queryDebtCustomer',
  queryUnpaidBillByCustId: SYS_URL1 + 'Bill/queryUnpaidBillByCustId',
  // 收款
  queryPaymentList: SYS_URL1 + 'payment/queryPaymentList',
  queryPaymentDetailList: SYS_URL1 + 'payment/queryPaymentDetailList',
  queryPaymentById: SYS_URL1 + 'payment/queryPaymentById',
  getShowRefno: SYS_URL1 + 'payment/getShowRefno',
  modifyPayment: SYS_URL1 + 'payment/modifyPayment',
  createPayment: SYS_URL1 + 'payment/createPayment',
  submit: SYS_URL1 + 'payment/submit',
  deletePayment: SYS_URL1 + 'payment/deletePayment',
  previewPayment: SYS_URL1 + 'payment/previewPayment',
  doPaymentTask: SYS_URL1 + 'payment/doPaymentTask',
  pay: SYS_URL1 + 'payment/pay',
  checkTasker: SYS_URL1 + 'payment/checkTasker',
  endorse: SYS_URL1 + 'payment/endorse',
  queryPayAccountByPermission: SYS_URL1 + 'payment/queryPayAccountByPermission',

  // 境外报价
  createSpecialTemplate: SYS_URL1 + 'offer/createSpecialTemplate',
  batchModifyPriceSortNo: SYS_URL1 + 'offer/batchModifyPriceSortNo',
  copyOfferPrice: SYS_URL1 + 'offer/copyOfferPrice',
  createOfferPrice: SYS_URL1 + 'offer/createOfferPrice',
  queryOfferPriceRules: SYS_URL1 + 'offer/queryOfferPriceRules',
  modifyOfferPrice: SYS_URL1 + 'offer/modifyOfferPrice',
  queryOfferPrice: SYS_URL1 + 'offer/queryOfferPrice',
  deleteOfferPrice: SYS_URL1 + 'offer/deleteOfferPrice',
  uploadImage: SYS_URL1 + 'offer/uploadImage',
  queryOfferPriceSome: SYS_URL1 + 'offer/queryOfferPriceSome',
  modifyOfferPriceSome: SYS_URL1 + 'offer/modifyOfferPriceSome',
  modifyOfferPriceM: SYS_URL1 + 'offer/modifyOfferPriceM',
  queryOfferPriceM: SYS_URL1 + 'offer/queryOfferPriceM',
  queryOfferCurrency: SYS_URL1 + 'offer/queryOfferCurrency',
  createOfferCurrency: SYS_URL1 + 'offer/createOfferCurrency',
  modifyOfferCurrency: SYS_URL1 + 'offer/modifyOfferCurrency',
  queryOfferCountries: SYS_URL1 + 'offer/queryOfferCountries',
  importOfferCust: SYS_URL1 + 'caseInfo/importOfferCust',
  queryOfferCust: SYS_URL1 + 'offer/queryOfferCust',
  queryCountryCn: SYS_URL1 + 'offer/queryCountryCn',
  createOfferCust: SYS_URL1 + 'offer/createOfferCust',
  modifyOfferCust: SYS_URL1 + 'offer/modifyOfferCust',
  createTemplateOffer: SYS_URL1 + 'offer/createTemplate',
  calculateOffer: SYS_URL1 + 'offer/calculateOffer',
  deleteOfferCust: SYS_URL1 + 'offer/deleteOfferCust',

  modifyMailInfo: SYS_URL1 + 'Outlook/modifyMailInfo',
  recordOnlienEdit: SYS_URL1 + 'material/recordOnlienEdit',
  batchDownloadCPCDocs: SYS_URL1 + 'material/batchDownloadCPCDocs',
  batchDownloadCPCExcel: SYS_URL1 + 'material/batchDownloadCPCExcel',
  userlogin: SYS_URL5 + 'auth/login',
  queryUserselfInfo: SYS_URL + 'auth/queryUser',
  userlogout: SYS_URL5 + 'auth/logout',
  // queryCustomerList: SYS_URL + 'customer/queryCustomerList',
  // delCustomer: SYS_URL + 'customer/delCustomer',
  // 部门管理
  queryDeptByCondition: SYS_URL + 'department/queryDeptByCondition',
  deleteDeptById: SYS_URL + 'department/deleteDeptById',
  queryDomainNames: SYS_URL + 'domain/queryDomainNames',
  selectAllDept: SYS_URL + 'department/selectAllDept',
  updateDeptById: SYS_URL + 'department/updateDeptById',
  createDept: SYS_URL + 'department/createDept',
  // 工作组
  queryWorkGroup: SYS_URL + 'workgroup/queryWorkGroup',
  queryZZWorkGroupUrl: SYS_URL + 'workgroup/queryZZWorkGroup',
  deleteWorkgroup: SYS_URL + 'workgroup/deleteWorkgroup',
  queryWorkgroupNames: SYS_URL + 'user/queryWorkgroupNames',
  selectWorkgroupById: SYS_URL + 'workgroup/selectWorkgroupById',
  queryUsers: SYS_URL + 'user/queryUsers',
  queryRoleNames: SYS_URL + 'user/queryRoleNames',
  createWorkgroup: SYS_URL + 'workgroup/createWorkgroup',
  updateById: SYS_URL + 'workgroup/updateById',
  // 员工
  queryCustPOAPerson: SYS_URL1 + 'caseUtil/queryCustPOAPerson',
  queryDeptGroupAndUser: SYS_URL1 + 'caseUtil/queryDeptGroupAndUser',
  getAreaList: SYS_URL1 + 'caseUtil/getAreaList',
  queryCaseRoleName: SYS_URL1 + 'caseUtil/queryCaseRoleName',
  queryAgentNumByCaseId: SYS_URL1 + 'caseUtil/queryAgentNumByCaseId',
  queryUserNames: SYS_URL + 'util/queryUserAll',
  queryPosition: SYS_URL + 'user/queryPosition',
  queryCustName: SYS_URL + 'user/queryCustName',
  addUser: SYS_URL + 'user/addUser',
  updateUser: SYS_URL + 'user/updateUser',
  addUserIcon: SYS_URL + 'user/addUserIcon',
  queryUserById: SYS_URL + 'user/queryUserById',
  deleteUser: SYS_URL + 'user/deleteUser',
  // 领域
  queryDomains: SYS_URL + 'domain/queryDomains',
  createDomain: SYS_URL + 'domain/createDomain',
  domainDelete: SYS_URL + 'domain/delete',
  domainUpdate: SYS_URL + 'domain/update',
  queryWorkgroupsByDomainId: SYS_URL + 'domain/queryWorkgroupsByDomainId',
  deleteGroupOrDeptById: SYS_URL + 'domain/deleteGroupOrDeptById',
  queryDepts: SYS_URL + 'domain/queryDepts',
  updateDeptOrWorkDominId: SYS_URL + 'domain/updateDeptOrWorkDominId',
  // 角色
  queryAllRoles: SYS_URL + 'role/queryAllRoles',
  deleteRoleById: SYS_URL + 'role/deleteRoleById',
  createRole: SYS_URL + 'role/createRole',
  queryUserIdByPermission: SYS_URL + 'role/queryUserByPermissionId',
  addUserForPermission: SYS_URL + 'role/addUserForPermission',
  updateRoleById: SYS_URL + 'role/updateRoleById',
  // 权限

  queryAllPermission: SYS_URL + 'permission/queryAllPermission',
  addPermissionForRole: SYS_URL + 'role/addPermissionForRole',
  queryRolesByPermissionId: SYS_URL + 'permission/queryRolesByPermissionId',
  addPermissionForUser: SYS_URL + 'role/addPermissionForUser',
  queryPermissionsByUserId: SYS_URL + 'permission/queryPermissionsByUserId',
  //  模板管理
  queryTemplateList: SYS_URL1+'pm/queryTemplateList',
  createTemplate: SYS_URL1+'/pm/createTemplate',
  deleteTemplate: SYS_URL1+'/pm/deleteTemplate',
  modifyTemplate: SYS_URL1+'/pm/modifyTemplate',
  addTaskGroup: SYS_URL1+'/pm/addTaskGroup',
  queryTaskList: SYS_URL1+'/pm/queryTaskList',
  modifyTaskGroup: SYS_URL1+'/pm/modifyTaskGroup',
  deleteTasks: SYS_URL1+'/pm/deleteTask',
  deleteTaskGroup: SYS_URL1+'/pm/deleteTaskGroup',
  addTask: SYS_URL1+'/pm/addTask',
  modifyTask: SYS_URL1+'/pm/modifyTask',
  addTemplateUser: SYS_URL1+'/pm/addTemplateUser',
  modifyTemplateUser: SYS_URL1+'/pm/modifyTemplateUser',
  deleteTemplateUser: SYS_URL1+'/pm/deleteTemplateUser',
  copyTemplate: SYS_URL1+'/pm/copyTemplate',
  // case
  createTask: SYS_URL1 + 'task/create',
  queryCaseType: SYS_URL1 + 'caseUtil/queryCaseType',
  queryUserRole: SYS_URL1 + 'caseUtil/queryUserRole',
  queryWorkGroupByUserId: SYS_URL1 + 'caseUtil/queryWorkGroupByUserId',
  queryReplaceAgencyName: SYS_URL1 + 'caseUtil/queryReplaceAgencyName',
  queryUserRate: SYS_URL1 + 'caseUtil/queryUserRate',
  deleteTask: SYS_URL1 + 'task/delete',
  // task
  createCode: SYS_URL1 + 'task/createCode',

  queryDeliver: SYS_URL1 + 'task/queryDeliver',
  //专利官费缴纳
  queryOfficialBillRecordList: SYS_URL1 + 'patentPay/queryOfficialBillRecordList',
  queryPayList: SYS_URL1 + 'patentPay/queryPayList',
  uploadPayReceipt: SYS_URL1 + 'patentPay/uploadPayReceipt',
  queryPatentPayCurrency: SYS_URL1 + 'patentPay/queryPatentPayCurrency',
  modifyPatentPayCurrency: SYS_URL1 + 'patentPay/modifyPatentPayCurrency',
  createFee: SYS_URL1 + 'patentPay/createFee',
  createPayExcel: SYS_URL1 + 'patentPay/createPayExcel',
  deletePatentPayList: SYS_URL1 + 'patentPay/deletePatentPayList',
  modifyPatentPayList: SYS_URL1 + 'patentPay/modifyPatentPayList',
  createPatentPayList: SYS_URL1 + 'patentPay/createPatentPayList',
  getPayListNo: SYS_URL1 + 'patentPay/getPayListNo',
  getSubmitOfficialsUrl: SYS_URL1 + 'submitOfficial/getSubmitOfficials',
  queryItemList: SYS_URL1 + 'submitOfficial/queryItemList',
  queryCaseInfoForZb: SYS_URL1 + 'submitOfficial/queryCaseInfoForZb',
  queryZbrecordList: SYS_URL1 + 'submitOfficial/queryZbrecordList',
  updateZbrecord: SYS_URL1 + 'submitOfficial/updateZbrecord',
  createZbrecord: SYS_URL1 + 'submitOfficial/createZbrecord',
  upSubmitOfficialsUrl: SYS_URL1 + 'submitOfficial/upSubmitOfficials',
  queryTrademarkCaseByOfficialTmFileIdsUrl: SYS_URL1 + 'officialInform/queryTrademarkCaseByOfficialTmFileIds',
  upTrademarkCaseByOfficialTmFileIdsUrl: SYS_URL1 + 'officialInform/upTrademarkCaseByOfficialTmFileIds',
  getBatchHerderUrl: SYS_URL1 + 'caseUtil/getBatchHerder',
  queryCaseByCaseIdsUrl: SYS_URL1 + 'trademarkCase/queryCaseByCaseIds',
  submitCaseClose: SYS_URL1 + 'trademarkCase/submitCaseClose',
  auditCaseClose: SYS_URL1 + 'trademarkCase/auditCaseClose',
  queryMaterialTypeUrl: SYS_URL1 + 'caseUtil/queryMaterialType',
  saveCasesUrl: SYS_URL1 + 'trademarkCase/saveCases',
  uploadFile: process.env.VUE_APP_BASE_API + SYS_URL1 + 'task/uploadFile',
  queryCasesByTaskId: SYS_URL1 + 'task/queryCasesByTaskId',
  selectColumn: SYS_URL1 + 'caseUtil/selectColumn',
  savePreference: SYS_URL1 + 'caseUtil/savePreference',
  queryCaseList: SYS_URL1 + 'trademarkCase/queryCaseList',
  getAllCaseInfo: SYS_URL1 + 'caseInfo/getAllCaseInfo',
  queryPreference: SYS_URL1 + 'caseUtil/queryPreference',
  delPreference: SYS_URL1 + 'caseUtil/delPreference',
  importTradeMarkCaseData: process.env.VUE_APP_BASE_API + SYS_URL1 + 'tmdata/importTradeMarkCaseData',
  queryFilter: SYS_URL1 + 'caseUtil/queryFilter',
  configFilter: SYS_URL1 + 'caseUtil/configFilter',
  queryFilterConfig: SYS_URL1 + 'caseUtil/queryFilterConfig',
  // 代办任务
  queryAlltask: SYS_URL1 + 'task/queryAll',
  copyCaseData: SYS_URL1 + 'taskdo/copyCaseData',
  queryZuoyeren: SYS_URL1 + 'taskdo/queryZuoyeren',
  chongtuTest: SYS_URL1 + 'taskdo/chongtuTest',
  tijiao: SYS_URL1 + 'taskdo/tijiao',
  chongtuAudit: SYS_URL1 + 'taskdo/chongtuAudit',
  // 任务管理
  addProjectTaskGroup: SYS_URL1 + 'pm/addProjectTaskGroup',
  queryProjectTask: SYS_URL1 + 'pm/queryProjectTask',
  modifyProjectTaskGroup: SYS_URL1 + 'pm/modifyProjectTaskGroup',
  deleteProjectTaskGroup: SYS_URL1 + 'pm/deleteProjectTaskGroup',
  addProjectTask: SYS_URL1 + 'pm/addProjectTask',
  modifyProjectTask: SYS_URL1 + 'pm/modifyProjectTask',
  deleteProjectTask: SYS_URL1 + 'pm/deleteProjectTask',
  assginTask: SYS_URL1 + 'pm/assginTask',
  submitTask: SYS_URL1 + 'pm/submitTask',
  auditTask: SYS_URL1 + 'pm/auditTask',
  queryToDoTask: SYS_URL1 + 'pm/queryToDoTask',
  addTaskHours: SYS_URL1 + 'pm/addTaskHours',
  startTaskHours: SYS_URL1 + 'pm/startTaskHours',
  stopTaskHours: SYS_URL1 + 'pm/stopTaskHours',
  queryTaskUserList: SYS_URL1 + 'pm/queryTaskUserList',
  queryUsersTaskList: SYS_URL1 + 'pm/queryUsersTaskList',
  delayTask: SYS_URL1 + 'pm/delayTask',
  shenpiTask: SYS_URL1 + 'pm/shenpiTask',
  addTaskItem: SYS_URL1 + 'pm/addTaskItem',
  modifyTaskItem: SYS_URL1 + 'pm/modifyTaskItem',
  deleteTaskItem: SYS_URL1 + 'pm/deleteTaskItem',
  createTmplateFile: SYS_URL1 + 'pm/createTmplateFile',
  queryTemplateFileList: SYS_URL1 + 'pm/queryTemplateFileList',
  bindTmplateFile: SYS_URL1 + 'pm/bindTmplateFile',
  unbindTmplateFile: SYS_URL1 + 'pm/unbindTmplateFile',
  bindTaskFile: SYS_URL1 + 'pm/bindTaskFile',
  unbindTaskFile: SYS_URL1 + 'pm/unbindTaskFile',
  copyTemplFile: SYS_URL1 + 'pm/copyTemplFile',
  modifyTaskMessage: SYS_URL1 + 'pm/modifyTaskMessage',
  modifyTaskNo: SYS_URL1 + 'pm/modifyTaskNo',
  deleteTemplateFile: SYS_URL1 + 'pm/deleteTemplateFile',
  createTemplateByPrj: SYS_URL1 + 'pm/createTemplateByPrj',
  queryProjecTeptId: SYS_URL1 + 'pm/queryProjecTeptId',


  // 工时管理
  hxWorkHoursToBill: SYS_URL1 + 'Bill/hxWorkHoursToBill',
  queryCaseBillList: SYS_URL1 + 'Bill/queryCaseBillList',
  queryWorkHourTask: SYS_URL1 + 'pm/queryWorkHourTask',
  updateWorkHourTasker: SYS_URL1 + 'pm/updateWorkHourTasker',
  queryWorkHours: SYS_URL1 + 'pm/queryWorkHours',
  queryWorkType: SYS_URL1 + 'pm/queryWorkType',
  queryActiveWorkgroupBossUserList: SYS_URL1 + 'caseUtil/queryActiveWorkgroupBossUserList',
  queryIfHehuoren: SYS_URL1 + 'caseUtil/queryIfHehuoren',
  queryCaseIdByAgentNum: SYS_URL1 + 'caseUtil/queryCaseIdByAgentNum',
  queryAutoWorkHours: SYS_URL1 + 'pm/queryAutoWorkHours',
  submitWorkHours: SYS_URL1 + 'pm/submitWorkHours',
  auditWorkHours: SYS_URL1 + 'pm/auditWorkHours',
  modifyTaskHours: SYS_URL1 + 'pm/modifyTaskHours',
  pauseTaskHours: SYS_URL1 + 'pm/pauseTaskHours',
  queryRecentCase: SYS_URL1 + 'pm/queryRecentCase',
  queryHourUserList: SYS_URL1 + 'pm/queryHourUserList',
  deleteTaskHours: SYS_URL1 + 'pm/deleteTaskHours',
  // 客户管理
  queryCustomerTask: SYS_URL1 + 'customer/queryCustomerTask',
  customerSubmit: SYS_URL1 + 'customer/customerSubmit',
  customerExamine: SYS_URL1 + 'customer/CustomerExamine',
  queryCustomerList: SYS_URL + 'customer/queryCustomerList', // 获取客户列表
  CustomerExamineUrl: SYS_URL + 'customer/CustomerExamine', // 获取客户列表
  queryCustomerNameId: SYS_URL + 'customer/queryCustomerNameId', // 获取客户
  delCustomer: SYS_URL + 'customer/delCustomer', // 删除客户
  addCustomer: SYS_URL + 'customer/addCustomer', // 添加客户
  querycustSelectClass: SYS_URL + 'util/queryClass',
  queryInventorList: SYS_URL1 + 'caseUtil/queryInventorList',//申请人中发明人列表
  queryBzdefineList: SYS_URL1 + 'caseUtil/queryBzdefineList',//补正文件名称列表
  queryZbliyou: SYS_URL1 + 'caseUtil/queryZbliyou',//著录变更理由
  queryZbzmfile: SYS_URL1 + 'caseUtil/queryZbzmfile',//著录变更理由对应的证明文件
  queryZbgroup: SYS_URL1 + 'caseUtil/queryZbgroup',//著录变更证明文件对应的分组类别
  queryLastDoc: SYS_URL1 + 'caseUtil/queryLastDoc',//查询案件最近的官方通知的发文日志和发文编号
  queryCurrencyUrl: SYS_URL + 'util/queryCurrency',
  queryPayAcountUrl: SYS_URL + 'util/queryPayAcount',
  queryFiliale: SYS_URL + 'util/queryFiliale',
  queryUserByPermissionId: SYS_URL + 'util/queryUserByPermissionId',
  queryCountry: SYS_URL + 'util/queryAddr',
  queryCPCAddr: SYS_URL + 'util/queryCPCAddr',
  queryPatentCountry: SYS_URL + 'util/queryPatentCountry',
  addCustomerAddrUrl: SYS_URL + 'Addr/addCustomerAddr',
  updateCustomerAddrUrl: SYS_URL + 'Addr/updateCustomerAddr',
  delCustomerAddrUrl: SYS_URL + 'Addr/delCustomerAddr',
  queryCustomerAddrAll: SYS_URL + 'Addr/queryCustomerAddrAll',
  addCustomerIcon: process.env.VUE_APP_BASE_API + SYS_URL + 'customer/addCustomerIcon',
  deleteCustomerIcon: SYS_URL + 'customer/deleteCustomerIcon',
  delCustomerReqDoc: SYS_URL + 'CustomerRequirement/delCustomerReqDoc',
  addCustomerContactIcon: process.env.VUE_APP_BASE_API + SYS_URL + 'customerContact/addCustomerContactIcon',
  deleteCustomerContactIcon: SYS_URL + 'customerContact/deleteCustomerContactIcon',
  addCustomerFile: process.env.VUE_APP_BASE_API + SYS_URL + 'customer/addCustomerFile',
  queryCustomerContactCustIdUrl: SYS_URL + 'customerContact/queryCustomerContactCustId',
  addCustomerContactUrl: SYS_URL + 'customerContact/addCustomerContact',
  queryBusinessAreaUrl: SYS_URL + 'customerContact/queryBusinessArea',
  updateCustomerContacturl: SYS_URL + 'customerContact/updateCustomerContact',
  delCustomerContacturl: SYS_URL + 'customerContact/delCustomerContact',
  delCustContactDoc: SYS_URL + 'customerContact/delCustContactDoc',
  addCustomerContactFileurl: process.env.VUE_APP_BASE_API + SYS_URL + 'customerContact/addCustomerContactFile',
  addCustomerRequirementFileUrl: process.env.VUE_APP_BASE_API +
    SYS_URL +
    'CustomerRequirement/addCustomerRequirementFile',
  queryCustomersUrl: SYS_URL + 'customer/queryCustomers',
  queryUserNamesUrl: SYS_URL + 'user/queryUsers',
  queryGroupsByUserId: SYS_URL + 'user/queryGroupsByUserId',
  addActivityUrl: SYS_URL + 'activity/addActivity',
  delActivity: SYS_URL + 'activity/delActivity',
  queryCustomerContactAgencyUrl: SYS_URL + 'customerContact/queryCustomerContactAgency',
  addCustomerContactAgencyUrl: SYS_URL + 'customerContact/addCustomerContactAgency',
  updateCustomerContactAgencyUrl: SYS_URL + 'customerContact/updateCustomerContactAgency',
  delCustomerContactAgencyUrl: SYS_URL + 'customerContact/delCustomerContactAgency',
  updateActivityUrl: SYS_URL + 'activity/updateActivity',
  queryCaseTypeUrl: SYS_URL + 'util/queryCaseType',
  querywfUserNameUrl: SYS_URL + 'agencycontact/queryUserName',
  allocationCustomerUrl: SYS_URL + 'agencycontact/allocationCustomer',
  queryAppAddrByAppIdUrl: SYS_URL + 'agencycontact/queryAppAddrByAppId',
  delAgencyContactUrl: SYS_URL + 'agencycontact/delAgencyContact',
  updateAgencyContactUrl: SYS_URL + 'agencycontact/updateAgencyContact',
  queryCustomerReqTypeUrl: SYS_URL + 'CustomerRequirement/queryCustomerReqType',
  queryregCaseTypeUrl: SYS_URL + 'CustomerRequirement/queryCaseType',
  addCustomerRequirementUrl: SYS_URL + 'CustomerRequirement/addCustomerRequirement',
  updateCustomerRequirementUrl: SYS_URL + 'CustomerRequirement/updateCustomerRequirement',
  delCustomerRequirementUrl: SYS_URL + 'CustomerRequirement/delCustomerRequirement',
  queryActivityListflUrl: SYS_URL + 'Conflicter/queryActivitys',
  addCustomerConflicterNew: SYS_URL + 'Conflicter/addCustomerConflicterNew',
  updateCustomerConflicterNew: SYS_URL + 'Conflicter/updateCustomerConflicterNew',
  queryConflicterListByCustIdNew: SYS_URL + 'Conflicter/queryConflicterListByCustIdNew',
  queryCustomerIndustry: SYS_URL + 'CustomerIndustry/queryCustomerIndustry',
  updateCustomerIndustry: SYS_URL + 'CustomerIndustry/updateCustomerIndustry',
  delCustomerIndustry: SYS_URL + 'CustomerIndustry/delCustomerIndustry',
  addCustomerIndustry: SYS_URL + 'CustomerIndustry/addCustomerIndustry',
  queryIndustryUrl: SYS_URL + 'CustomerIndustry/queryIndustry',
  queryCustomerUrl: SYS_URL + 'customer/queryCustomer',
  queryCustomerByBillorCase: SYS_URL + 'customer/queryCustomerByBillorCase',
  updateCustomerUrl: SYS_URL + 'customer/updateCustomer',
  queryCustKuaijieCounts: SYS_URL + 'customer/queryCustKuaijieCounts',
  queryCustStatistics: SYS_URL + 'customer/queryCustStatistics',
  queryWarningStatistics: SYS_URL + 'customer/queryWarningStatistics',
  queryNewCustYejiDetail: SYS_URL + 'customer/queryNewCustYejiDetail',
  queryIncomeByMonth: SYS_URL + 'customer/queryIncomeByMonth',
  queryGroupIncomeByMonth: SYS_URL + 'customer/queryGroupIncomeByMonth',
  queryExpectIncomeByMonth: SYS_URL + 'customer/queryExpectIncomeByMonth',
  queryGroupExpectIncomeByMonth: SYS_URL + 'customer/queryGroupExpectIncomeByMonth',
  queryWarningList: SYS_URL + 'customer/queryWarningList',
  queryIncomeByYear: SYS_URL + 'customer/queryIncomeByYear',
  queryGroupIncomeByYear: SYS_URL + 'customer/queryGroupIncomeByYear',
  addCustomerAssociate: SYS_URL + 'CustomerAssociate/addCustomerAssociate',
  updateCustomerAssociate: SYS_URL + 'CustomerAssociate/updateCustomerAssociate',
  delCustomerAssociate: SYS_URL + 'CustomerAssociate/delCustomerAssociate',
  queryCustomerAssociate: SYS_URL + 'CustomerAssociate/queryCustomerAssociate',
  updateCustomerNew: SYS_URL + 'customer/updateCustomerNew',
  queryCustTree: SYS_URL + 'customer/queryCustTree',
  queryCustAndFenzhiInfo: SYS_URL + 'customer/queryCustAndFenzhiInfo',
  queryCustContactTree: SYS_URL + 'customer/queryCustContactTree',
  queryCustomerNameIdUrl: SYS_URL + 'customer/queryCustomerNameId',
  queryCustCoverPage: SYS_URL + 'customer/queryCustCoverPage',
  queryCustomerListNew: SYS_URL + 'customer/queryCustomerListNew',
  queryCustomerCardNew: SYS_URL + 'customer/queryCustomerCardNew',
  delUserFollowCust: SYS_URL + 'customer/delUserFollowCust',
  addUserFollowCust: SYS_URL + 'customer/addUserFollowCust',
  addUserCustSort: SYS_URL + 'customer/addUserCustSort',
  queryCountryUrl: SYS_URL + 'util/queryCountry',
  ifNewLevel: SYS_URL1 + 'caseUtil/ifNewLevel',
  queryCountryCaseUrl: SYS_URL1 + 'caseUtil/queryCountry',
  queryCountryTm: SYS_URL1 + 'caseUtil/queryCountryTm',
  queryCaseStageTm: SYS_URL1 + 'caseUtil/queryCaseStageTm',
  addCaseEventUrl: SYS_URL1 + 'trademarkCase/addCaseEvent',
  analysisFile: 'ip_wordToPdf/interface/' + 'trademarkCase/analysisFile',
  fileMergePdf: 'ip_wordToPdf/interface/' + 'patentMaterial/fileMergePdf',
  mergePdf: 'ip_wordToPdf/interface/' + 'patentMaterial/mergePdf',
  deleteCaseEventUrl: SYS_URL1 + 'trademarkCase/deleteCaseEvent',
  deleteMail: SYS_URL1 + 'trademarkCase/deleteMail',
  updateCaseEventUrl: SYS_URL1 + 'trademarkCase/updateCaseEvent ',
  updateLevelUrl: SYS_URL + 'customer/updateLevel',
  queryCustomerContactListUrl: SYS_URL + 'customerContact/queryCustomerContactList',
  queryCustomerContactUrl: SYS_URL + 'customerContact/queryCustomerContact',
  queryCustContactAllUrl: SYS_URL + 'customerContact/queryCustContactAll',
  queryhuodongList: SYS_URL + 'activity/queryhuodongList',
  queryActivityListUrl: SYS_URL + 'activity/queryActivityList',
  queryCaseByUserUrl: SYS_URL + 'util/queryCaseByUser',
  queryActivityOneUrl: SYS_URL + 'activity/queryActivityOne',
  queryCustomerAddrUrl: SYS_URL + 'Addr/queryCustomerAddr',
  queryAgencyContactUrl: SYS_URL + 'agencycontact/queryAgencyContact',
  queryCustomerRequirementUrl: SYS_URL + 'CustomerRequirement/queryCustomerRequirement',
  // queryCustomerContactListUrl: SYS_URL + 'customerContact/queryCustomerContactList',
  // queryCustomerContactUrl: SYS_URL + 'customerContact/queryCustomerContact',
  // 申请人
  queryAllUrl: SYS_URL + 'agencycontact/queryAll',
  queryApplication: SYS_URL + 'agencycontact/queryApplication',

  // 市场活动
  queryNewCustYeji: SYS_URL1 + 'newcust/queryNewCustYeji',
  queryDataForOneUser: SYS_URL1 + 'newcust/queryDataForOneUser',
  queryCustDetail: SYS_URL1 + 'newcust/queryCustDetail',

  queryContactByName: SYS_URL + 'contactManage/queryContactByName',

  queryCountrysUrl: SYS_URL + 'agencycontact/queryCountrys',
  queryOtherCustomerListUrl: SYS_URL + 'customer/queryOtherCustomerList',
  deleteUrl: SYS_URL + 'agencycontact/delete',
  updateUrl: SYS_URL + 'agencycontact/update',
  createUrl: SYS_URL + 'agencycontact/create',
  queryDetailByIdUrl: SYS_URL + 'agencycontact/queryDetailById',
  querylyctListUrl: SYS_URL + 'Conflicter/queryActivityList',
  delConflicterUrl: SYS_URL + 'Conflicter/delConflicter',
  delCustomerConflicter: SYS_URL + 'Conflicter/delCustomerConflicter',
  addCustomerConflicter: SYS_URL + 'Conflicter/addCustomerConflicter',
  addConflicterUrl: SYS_URL + 'Conflicter/addConflicter',
  updateCustomerConflicterUrl: SYS_URL + 'Conflicter/updateCustomerConflicter',
  queryCustomerConflicterUrl: SYS_URL + 'Conflicter/queryCustomerConflicter',
  updateBankaccountUrl: SYS_URL + 'customerBankaccount/updateBankaccount',
  addBankaccountUrl: SYS_URL + 'customerBankaccount/addBankaccount',
  delBankaccountUrl: SYS_URL + 'customerBankaccount/delBankaccount',

  //发布列表
  queryReleaseList: SYS_URL + 'releases/queryReleaseList',
  modifyRelease: SYS_URL + 'releases/modifyRelease',
  createRelease: SYS_URL + 'releases/createRelease',
  queryReleaseById: SYS_URL + 'releases/queryReleaseById',
  deleteRelease: SYS_URL + 'releases/deleteRelease',

  // 案件详情
  queryPatentCaseInfo: SYS_URL1 + 'patentCase/queryCaseInfo',
  queryOrigCaseInfo: SYS_URL1 + 'patentCase/queryOrigCaseInfo',
  queryUserCaseNumber: SYS_URL1 + 'patentCase/queryUserCaseNumber',
  queryCaseAgentNumList: SYS_URL1 + 'patentCase/queryCaseAgentNumList',
  queryCaseInfoUrl: SYS_URL1 + 'trademarkCase/queryCaseInfo',
  queryParentCaseDocNumber: SYS_URL1 + 'lawsuit/queryParentCaseDocNumber',
  lawsuitUrl: SYS_URL1 + 'lawsuit/queryCaseInfo',
  queryLawCaseClause: SYS_URL1 + 'lawsuit/queryLawCaseClause',
  officialCaseUrl: SYS_URL1 + 'trademarkCase/officialCase',
  saveCaseInfoUrl: SYS_URL1 + 'taskdo/saveCaseInfo',
  billSubmitUrl: SYS_URL1 + 'taskdo/billSubmit',
  queryCustomerContactByCustContactIdUrl: SYS_URL1 + 'caseUtil/queryCustomerContactByCustContactId',
  queryCustomerContactByCustIdUrl: SYS_URL1 + 'caseUtil/queryCustomerContactByCustId',
  queryAppInfoUrl: SYS_URL1 + 'caseUtil/queryAppInfo',
  queryAppContactUrl: SYS_URL1 + 'caseUtil/queryAppContact',
  queryCustomerReqUrl: SYS_URL1 + 'caseUtil/queryCustomerReq',
  queryCaseWorkgroupUrl: SYS_URL1 + 'caseUtil/queryCaseWorkgroup',
  importExcel: SYS_URL1 + 'gsq/importExcel',
  queryListByUrl: SYS_URL1 + 'gsq/queryListBy',
  addGoodsPlanUrl: SYS_URL1 + 'gsq/addGoodsPlan',
  queryGoodsByAgentNumUrl: SYS_URL1 + 'gsq/queryGoodsByAgentNum',
  cradeJoinAppUrl: SYS_URL1 + 'trademarkCaseJoinApp/cradeJoinApp',
  delJoinAppUrl: SYS_URL1 + 'trademarkCaseJoinApp/delJoinApp',
  modifyjoinappUrl: SYS_URL1 + 'trademarkCaseJoinApp/modifyjoinapp',
  oneKeyZipUrl: SYS_URL1 + 'trademarkCase/oneKeyZip',
  heighCreditUrl: SYS_URL1 + 'taskdo/heighCredit',
  handoverCase: SYS_URL1 + 'taskdo/handoverCase',
  auditCase: SYS_URL1 + 'taskdo/auditCase',
  checkForbidContentUrl: SYS_URL1 + 'ipinfo/checkForbidContent',
  checkSameTmUrl: SYS_URL1 + 'ipinfo/checkSameTm',
  queryGoodsPlanUrl: SYS_URL1 + 'gsq/queryGoodsPlan',
  deleteGoodsPlanUrl: SYS_URL1 + 'gsq/deleteGoodsPlan',
  queryGoodsUrl: SYS_URL1 + 'gsq/queryGoods',
  GSQQueryAllClassUrl: '/GSQ/GSQ/GSQQueryAllClass',
  GSQQueryFirstClassUrl: '/GSQ/GSQ/GSQQueryFirstClass',
  GSQQueryClassUrl: '/GSQ/GSQ/GSQQueryClass',
  queryDetaileGroupUrl: '/GSQ/GSQ/queryDetaileGroup',
  queryByNameUrl: '/GSQ/GSQ/queryByName',
  GSQAllcategoryUrl: '/GSQ/GSQ/GSQAllcategory',
  GSQCategoryUrl: '/GSQ/GSQ/queryCategory',
  // GSQQueryAllClassUrl: 'GSQ/GSQ/GSQQueryAllClass',
  // GSQAllcategoryUrl: '/GSQ/GSQ/GSQAllcategory',
  creatematerialUrl:`${window.location.origin}/ip_service/interface/material/creatematerial`,
  checkImageInstruction: SYS_URL1 + 'material/checkImageInstruction',
  delCaseMaterialUrl: SYS_URL1 + 'material/delCaseMaterial',
  queryFileNameDefine: SYS_URL1 + 'material/queryFileNameDefine',// 查询预先定义的文件命名方式
  queryFileNameElement: SYS_URL1 + 'material/queryFileNameElement',// 查询文件命名自定义元素
  createPatentMultMaterial: SYS_URL1 + 'material/createPatentMultMaterial',
  queryMaterialByCaseIdUrl: SYS_URL1 + 'material/queryMaterialByCaseId',
  queryMaterialByUserIdAndYear: SYS_URL1 + 'material/queryMaterialByUserIdAndYear',
  // 账单
  queryBillStyle: SYS_URL1 + 'caseUtil/queryBillStyle',
  queryAgentUser: SYS_URL1 + 'caseUtil/queryAgentUser',
  modifyBillBadDebtBatch: SYS_URL1 + 'Bill/modifyBillBadDebtBatch',
  modifyBillBatch: SYS_URL1 + 'Bill/modifyBillBatch',
  modifyBillBalanceBatch: SYS_URL1 + 'Bill/modifyBillBalanceBatch',
  queryBillListUrl: SYS_URL1 + 'Bill/queryBillList',
  queryRecentBillList: SYS_URL1 + 'Bill/queryRecentBillList',
  queryCaseListByBillId: SYS_URL1 + 'Bill/queryCaseListByBillId',
  writeOffBillRecordUrl: SYS_URL1 + 'Bill/writeOffBillRecord',
  queryBillUrl: SYS_URL1 + 'Bill/queryBill',
  queryBillByBillNo: SYS_URL1 + 'Bill/queryBillByBillNo',
  saveBillRecord: SYS_URL1 + 'billRecord/saveBillRecord',
  queryBillRecordListUrl: SYS_URL1 + 'billRecord/queryBillRecordList',
  billRecorddeleteUrl: SYS_URL1 + 'billRecord/delete',
  queryBillInternalListUrl: SYS_URL1 + 'BillInternal/queryBillInternalList',
  deleteBillInternalUrl: SYS_URL1 + 'BillInternal/deleteBillInternal',
  writeOffBillRecordnbUrl: SYS_URL1 + 'BillInternal/writeOffBillRecord',
  queryBillInternalUrl: SYS_URL1 + 'BillInternal/queryBillInternal',
  queryWorkgroupUrl: SYS_URL1 + 'caseUtil/queryWorkgroup',
  queryWkgId: SYS_URL1 + 'caseUtil/queryWkgId',
  queryCustGroup: SYS_URL1 + 'caseUtil/queryCustGroup',
  updateBillInternalUrl: SYS_URL1 + 'BillInternal/updateBillInternal',
  singleSubmitBillInternalUrl: SYS_URL1 + 'BillInternal/singleSubmitBillInternal',
  queryBillRecordcdUrl: SYS_URL1 + 'billRecord/queryBillRecord',
  updateBillRecordUrl: SYS_URL1 + 'billRecord/updateBillRecord',
  // queryCurrencyUrl: SYS_URL + 'util/queryCurrency',
  queryChargeItemBynameCnUrl: SYS_URL1 + 'Bill/queryChargeItemBynameCn',
  queryCaseSurplusList: SYS_URL1 + 'trademarkCase/queryCaseSurplusList',
  exportCaseSurplusList: SYS_URL1 + 'trademarkCase/exportCaseSurplusList',
  selecttrademarkUrl: SYS_URL1 + 'trademark/selecttrademark',
  querytmxuzhanUrl: SYS_URL1 + 'trademark/querytmxuzhan',
  querytmchangeUrl: SYS_URL1 + 'trademark/querytmchange',
  tmdetailUrl: SYS_URL1 + 'trademark/tmdetail',
  tmdetailUrl3: SYS_URL3 + 'tmdata/tmdetail',
  queryChargeItemUrl: SYS_URL + 'CustomerRequirement/queryChargeItem',
  queryCustomerRequirementBycustIdUrl: SYS_URL + 'CustomerRequirement/queryCustomerRequirementBycustId',
  topCustomerRequirement: SYS_URL + 'CustomerRequirement/topCustomerRequirement',

  queryBillRecordUrl: SYS_URL1 + 'Bill/queryBillRecord',
  createBillUrl: SYS_URL1 + 'Bill/singleSubmitBill',
  checkWkg: SYS_URL1 + 'Bill/checkWkg',
  deleteBillAllocation: SYS_URL1 + 'Bill/deleteBillAllocation',
  updateBillUrl: SYS_URL1 + 'Bill/updateBill',
  deleteBillUrl: SYS_URL1 + 'Bill/deleteBill',
  batchdoBillTaskUrl: SYS_URL1 + 'Bill/batchdoBillTask',
  updateBillRemarksUrl: SYS_URL1 + 'Bill/updateBillRemarks',
  updateBillDateAndBelongToDateUrl: SYS_URL1 + 'Bill/updateBillDateAndBelongToDate',
  querySingleBillUrl: SYS_URL1 + 'Bill/querySingleBill',
  querydotaskBillUrl: SYS_URL1 + 'Bill/querydotaskBill',
  checkIsSameCustUrl: SYS_URL1 + 'Bill/checkIsSameCust',
  createSumBillNoUrl: SYS_URL1 + 'Bill/createSumBillNo',
  queryCaseEventListUrl: SYS_URL1 + 'trademarkCase/queryCaseEventList',
  queryCaseEventDetailUrl: SYS_URL1 + 'trademarkCase/queryCaseEventDetail',
  queryBillInternalTaskListUrl: SYS_URL1 + 'BillInternal/queryBillInternalTaskList',
  doBillInternalTaskUrl: SYS_URL1 + 'BillInternal/doBillInternalTask',
  queryCustomerAddrListUrl: SYS_URL + 'Addr/queryCustomerAddrList',
  queryAgencyContactListUrl: SYS_URL + 'agencycontact/queryAgencyContactList',
  queryAddrByAppIds: SYS_URL + 'agencycontact/queryAddrByAppIds',
  queryCustomerContactAddrUrl: SYS_URL + 'customerContact/queryCustomerContactAddr',
  queryCustomerContactByCustIdUrl1: SYS_URL + 'customerContact/queryCustomerContactByCustId',
  queryConflicterListByCustId: SYS_URL + 'Conflicter/queryConflicterListByCustId',
  queryConflicterListUrl: SYS_URL + 'Conflicter/queryConflicterList',
  searchtmdataUrl: SYS_URL2 + 'trademark/searchtmdata',
  searchTmUrl: SYS_URL3 + 'tmdata/searchTm',
  tmdetailsearUrl: SYS_URL3 + 'tmdata/tmdetail',
  menusUrl: SYS_URL4 + 'dashboard/menus',
  statsUrl: SYS_URL4 + 'dashboard/stats',
  queryBillTemplateUrl: SYS_URL1 + 'form/queryBillTemplate',
  querySpecialTemplates: SYS_URL1 + 'form/querySpecialTemplates',
  queryAbroadBillTemplate: SYS_URL1 + 'form/queryAbroadBillTemplate',
  createTmCaseQuotesTemplate: SYS_URL1 + 'form/createTmCaseQuotesTemplate',
  createAbroadBillTemplate: SYS_URL1 + 'form/createAbroadBillTemplate',
  createBillTemplateUrl: SYS_URL1 + 'form/createBillTemplate',
  queryBillSum: SYS_URL1 + 'Bill/queryBillSum',
  queryChargeItemList: SYS_URL1 + 'chargeItem/queryChargeItemList',
  deleteChargeItem: SYS_URL1 + 'chargeItem/deleteChargeItem',
  queryChargeItemInfo: SYS_URL1 + 'chargeItem/queryChargeItemInfo',
  updateChargeItem: SYS_URL1 + 'chargeItem/updateChargeItem',
  addChargeItemInfo: SYS_URL1 + 'chargeItem/addChargeItemInfo',
  queryCustomerListByUserId: SYS_URL1 + 'customer/queryCustomerListByUserId',
  checkWkgIsGj: SYS_URL + 'department/checkWkgIsGj',
  queryHXBillData: SYS_URL1 + 'Bill/queryHXBillData',
  delCustomerFile: SYS_URL + 'customer/delCustomerFile',
  queryCaseGory: SYS_URL1 + 'CaseGory/queryCaseGoryContact',
  deleteMaterial: SYS_URL + 'Conflicter/deleteMaterial',
  queryQuoteByNumber: SYS_URL1 + 'trademarkCaseQuote/queryQuoteByNumber',

  // 仪表盘
  getAllPanels: SYS_URL6 + 'statistics/getAllPanels',
  hideShowUserPanel: SYS_URL6 + 'statistics/hideShowUserPanel',
  getChartData: SYS_URL6 + 'dashboard/getChartData',
  queryConfigFilter: SYS_URL6 + 'statistics/queryConfigFilter',
  addFilterScheme: SYS_URL6 + 'statistics/addFilterScheme',
  getFilterScheme: SYS_URL6 + 'statistics/getFilterScheme',
  deleteFilterScheme: SYS_URL6 + 'statistics/deleteFilterScheme',
  queryFilter1: SYS_URL6 + 'statistics/queryFilter',
  configFilter1: SYS_URL6 + 'statistics/configFilter',
  getStatisticsProperty: SYS_URL6 + 'statistics/getStatisticsProperty',
  getPropertyPreference: SYS_URL6 + 'statistics/getPropertyPreference',
  deletePropertyPreference: SYS_URL6 + 'statistics/deletePropertyPreference',
  savePropertyPreference: SYS_URL6 + 'statistics/savePropertyPreference',
  queryChartDateItems: SYS_URL6 + 'statistics/queryChartDateItems',
  exportChartDataItems: SYS_URL6 + 'statistics/exportChartDataItems',
  exportChartPDF: SYS_URL6 + 'statistics/exportChartPDF',
  exportNewChartPPt: SYS_URL6 + 'statistics/exportNewChartPPt',
  exportChartPPt: SYS_URL6 + 'statistics/exportChartPPt',
  queryCustomList: SYS_URL6 + 'customType/query',
  createAndModify: SYS_URL6 + 'customType/createAndModify',
  queryCustomerCard: SYS_URL6 + 'dashboard/queryCustomerCard', //高级工作台客户卡片列表
  queryCustomerInfo: SYS_URL6 + 'dashboard/queryCustomerInfo', //高级工作台客户信息
  queryCustomerMap: SYS_URL6 + 'dashboard/queryCustomerMap', //高级工作台全球客户信息分布
  deriveSYTable: SYS_URL6 + 'dashboard/deriveSYTable', //损益表下载

  //重要事项
  queryImportantMatters: SYS_URL6 + 'dashboard/queryImportantMatters',
  settingsNoticeRead: SYS_URL6 + 'dashboard/settingsNoticeRead',
  queryNoticeImpl: SYS_URL6 + 'dashboard/queryNoticeImpl',
  queryCaseNotice: SYS_URL6 + 'dashboard/queryCaseNotice',
  queryCustNotice: SYS_URL6 + 'dashboard/queryCustNotice',

  // 重要事项订阅范围
  settingsSubscribeRange: SYS_URL1 + 'caseUtil/settingsSubscribeRange',
  querySubscribeRange: SYS_URL1 + 'caseUtil/querySubscribeRange',

  //订阅事件
  settingsSubscribe: SYS_URL1 + 'caseUtil/settingsSubscribe',
  querySubscribe: SYS_URL1 + 'caseUtil/querySubscribe',

  // 合作资源，代理所
  queryColAgencyList: SYS_URL + 'customer/queryColAgencyList',
  queryColAgencyItemList: SYS_URL1 + 'customer/queryColAgencyItemList',
  exportColAgencyItemList: SYS_URL1 + 'customer/exportColAgencyItemList',
  queryColAgency: SYS_URL + 'customer/queryColAgency',
  queryColAgencyInfo: SYS_URL + 'customer/queryColAgencyInfo',
  updateColAgencyInfo: SYS_URL + 'customer/updateColAgencyInfo',
  addColAgencyInfo: SYS_URL + 'customer/addColAgencyInfo',

  // 内外资料管理
  deleteDir: SYS_URL1 + 'material/deleteDir',
  createDir: SYS_URL1 + 'material/createDir',
  queryNwDocTypeList: SYS_URL1 + 'material/queryNwDocTypeList',
  queryContinent: SYS_URL1 + 'caseUtil/queryContinent', // 查询大洲国家
  queryAgentPerson: SYS_URL1 + 'caseUtil/queryAgentPerson',
  queryContinentByWorldArea: SYS_URL1 + 'caseUtil/queryContinentByWorldArea', // 查询大洲国家
  queryCountryList: SYS_URL1 + 'caseUtil/queryCountryList', // 查询国家/地区列表
  queryCountryAgency: SYS_URL1 + 'caseUtil/queryCountryAgency',
  queryNwCaseTypeList: SYS_URL1 + 'caseUtil/queryNwCaseTypeList', // 查询案件类型
  querySortPermission: SYS_URL1 + 'material/querySortPermission',
  updateSortPermission: SYS_URL1 + 'material/updateSortPermission',
  queryNwMaterial: SYS_URL1 + 'material/queryNwMaterial',
  createNwCaseType: SYS_URL1 + 'material/createNwCaseType', // 增加案件类型
  createNwMaterial: SYS_URL1 + 'material/createNwMaterial', // 创建文件
  deleteNwMaterial: SYS_URL1 + 'material/deleteNwMaterial', // 删除文件
  modifyNwMaterial: SYS_URL1 + 'material/modifyNwMaterial', // 修改文件
  modifyDir: SYS_URL1 + 'material/modifyDir', // 重命名、移动文件夹
  moveNwMaterialAndDir: SYS_URL1 + 'material/moveNwMaterialAndDir', // 移动文件/夹
  copyNwMaterialAndDir: SYS_URL1 + 'material/copyNwMaterialAndDir', // 复制文件/夹

  // 档案管理
  queryArchivesList: SYS_URL1 + 'archives/queryArchivesList', // 档案信息列表
  batchUpdateArchives: SYS_URL1 + 'archives/batchUpdateArchives', // 档案批量编辑
  createArchives: SYS_URL1 + 'archives/createArchives', // 新建档案
  updateArchives: SYS_URL1 + 'archives/updateArchives', // 修改档案
  queryArchivesInfo: SYS_URL1 + 'archives/queryArchivesInfo', // 查询档案信息
  delArchives: SYS_URL1 + 'archives/delArchives', // 删除档案信息
  copyArchives: SYS_URL1 + 'archives/copyArchives', // 复制档案
  updateArchivesStatus: SYS_URL1 + 'archives/updateArchivesStatus', // 更新档案状态（借出、归还、取走、异地保存、销毁)
  uploadArchivesOriginalFile: SYS_URL1 + 'archives/uploadArchivesOriginalFile', // 上传原件附件自动识别类型和名称
  uploadArchivesMaterial: SYS_URL1 + 'archives/uploadArchivesMaterial', // 上传档案相关附件
  initArchivesOriginalFile: SYS_URL1 + 'archives/uploadArchivesOriginalFile', // 识别原件
  deleteArchivesMaterial: SYS_URL1 + 'archives/deleteArchivesMaterial', // 删除附件解除和档案关联
  exportArchivesBack: SYS_URL1 + 'archives/exportArchivesBack', // 导出档案信息案卷脊背
  exportLendArchivesPortrait: SYS_URL1 + 'archives/exportLendArchivesPortrait', // 导出档案信息【借出案卷】（纵向）
  exportLendArchivesCrossWise: SYS_URL1 + 'archives/exportLendArchivesCrossWise', // 导出档案信息【借出原件】
  exportArchivesTakeAway: SYS_URL1 + 'archives/exportArchivesTakeAway', // 取走
  exportArchivesRemoteStore: SYS_URL1 + 'archives/exportArchivesRemoteStore', // 异地保存
  queryArchivesAndSampleList: SYS_URL1 + 'archives/queryArchivesAndSampleList', // 查询案件详情档案、合同及样品列表
  queryArchivesStatusByBarcode: SYS_URL1 + 'archives/queryArchivesStatusByBarcode', // 根据条码号查询档案状态等信息
  statisticsManagerOperationTimes: SYS_URL1 + 'archives/statisticsManagerOperationTimes', // 工作量统计
  statisticsAgentNumsCount: SYS_URL1 + 'archives/statisticsAgentNumsCount',

  // 样品管理
  querySampleList: SYS_URL1 + 'sample/querySampleList', // 样品信息列表
  createSample: SYS_URL1 + 'sample/createSample', // 新建样品
  updateSample: SYS_URL1 + 'sample/updateSample', // 编辑样品
  querySampleInfo: SYS_URL1 + 'sample/querySampleInfo', // 查询样品信息
  copySample: SYS_URL1 + 'sample/copySample', // 复制样品
  delSample: SYS_URL1 + 'sample/delSample', // 删除样品
  updateSampleStatus: SYS_URL1 + 'sample/updateSampleStatus', // 更新样品状态（借出、归还、取走、异地保存、销毁）
  uploadSampleMaterial: SYS_URL1 + 'sample/uploadSampleMaterial', // 上传样品相关附件
  deleteSampleMaterial: SYS_URL1 + 'sample/deleteSampleMaterial', // 删除附件解除和样品关联
  exportSampleLendOut: SYS_URL1 + 'sample/exportSampleLendOut', // 借出
  exportSampleSendOut: SYS_URL1 + 'sample/exportSampleSendOut', // 寄出
  exportSampleDestroy: SYS_URL1 + 'sample/exportSampleDestroy', // 销毁
  batchUpdateSamples: SYS_URL1 + 'sample/batchUpdateSamples',
  sampleWorkloadStatistics: SYS_URL1 + 'sample/statisticsManagerOperationTimes', // 工作量统计

  // 合伙人周报
  uploadFlashMaterial: SYS_URL1 + 'material/uploadFlashMaterial', // 上传快讯
  queryReportList: SYS_URL1 + 'report/queryReportList',
  queryReportDetail: SYS_URL1 + 'report/queryReportDetail',
  queryWeekReportDoc: SYS_URL1 + 'report/queryWeekReportDoc',
  createWeekReportDoc: SYS_URL1 + 'report/createWeekReportDoc',
  manualScoring: SYS_URL1 + 'report/dafen',
  queryCaidingList: SYS_URL1 + 'flash/queryCaidingList',
  createCaiding: SYS_URL1 + 'flash/createCaiding',
  updateCaiding: SYS_URL1 + 'flash/updateCaiding',
  delCaiding: SYS_URL1 + 'flash/delCaiding',
  queryRongyuList: SYS_URL1 + 'flash/queryRongyuList',
  createRongyu: SYS_URL1 + 'flash/createRongyu',
  updateRongyu: SYS_URL1 + 'flash/updateRongyu',
  delRongyu: SYS_URL1 + 'flash/delRongyu',
  queryNeibuGuanliList: SYS_URL1 + 'flash/queryNeibuGuanliList',
  queryNeibuGuanliInfo: SYS_URL1 + 'flash/queryNeibuGuanliInfo',
  createNeibuGuanli: SYS_URL1 + 'flash/createNeibuGuanli',
  updateNeibuGuanli: SYS_URL1 + 'flash/updateNeibuGuanli',
  delNeibuGuanli: SYS_URL1 + 'flash/delNeibuGuanli',
  queryRenliList: SYS_URL1 + 'flash/queryRenliList',
  createRenli: SYS_URL1 + 'flash/createRenli',
  updateRenli: SYS_URL1 + 'flash/updateRenli',
  delRenli: SYS_URL1 + 'flash/delRenli',
  queryXuanchuanList: SYS_URL1 + 'flash/queryXuanchuanList',
  createXuanchuan: SYS_URL1 + 'flash/createXuanchuan',
  updateXuanchuan: SYS_URL1 + 'flash/updateXuanchuan',
  delXuanchuan: SYS_URL1 + 'flash/delXuanchuan',

  // 律所绩效
  queryJixiao: SYS_URL1 + 'report/queryJixiao',
  queryJixiaoRule: SYS_URL1 + 'report/queryJixiaoRule',
  modifyJixiaoRule: SYS_URL1 + 'report/modifyJixiaoRule',

  //工作台账单收入
  queryIncomeByYearAndMonth: SYS_URL + 'customer/queryIncomeByYearAndMonth',

  //查询外方代理所接口
  queryCollaborationAll: SYS_URL + 'customer/queryCollaborationAll',

  //工作台
  queryWorkbenchModule:SYS_URL + 'workbench/queryWorkbenchModule',
  queryWorkbenchConfig:SYS_URL + 'workbench/queryWorkbenchConfig',
  saveWorkbenchConfig:SYS_URL + 'workbench/saveWorkbenchConfig',

  //出差管理
  submitBusinessTrip:SYS_URL + 'businessTrip/submit',
  saveBusinessTrip:SYS_URL + 'businessTrip/save',
  auditBusinessTrip:SYS_URL + 'businessTrip/audit',
  countTripDays:SYS_URL + 'businessTrip/countTripDays',
  getBtList:SYS_URL + 'businessTrip/getList',
  getBtById:SYS_URL + 'businessTrip/getById',
  deleteBtById:SYS_URL + 'businessTrip/deleteById',
  checkListType:SYS_URL + 'businessTrip/checkListType',
  queryTodoTask:SYS_URL + 'businessTrip/queryTodoTask',

  //高级工作台待办任务总数
  getSumForWorkbench:SYS_URL1 + 'caseUtil/getSumForWorkbench',

  //客户联系人相关事项
  getMatterList:SYS_URL + 'custConMat/getMatterList',
  createMatter:SYS_URL + 'custConMat/createMatter',
  updateMatter:SYS_URL + 'custConMat/updateMatter',
  deleteMatter:SYS_URL + 'custConMat/deleteMatter',

  //客户重大事件
  getEventList:SYS_URL + 'custEvent/getEventList',
  queryCustEventDetail:SYS_URL + 'custEvent/queryEvent',
  getCompanyName:SYS_URL + 'custEvent/getCompanyName',
  createEvent:SYS_URL + 'custEvent/createEvent',
  updateEvent:SYS_URL + 'custEvent/updateEvent',
  deleteEvent:SYS_URL + 'custEvent/deleteEvent',

  //Excel导出
  deriveDJDTable:SYS_URL6 + 'dashboard/deriveDJDTable',

  //我的关注
  queryFollowCasesByUserId: SYS_URL1 + 'caseInfo/queryFollowCasesByUserId',
  queryImportantCasesByUserId: SYS_URL1 + 'caseInfo/queryImportantCasesByUserId',

  //案件管理文件夹
  statisticCase: SYS_URL1 + 'caseInfo/statisticCase',

  //案件封面
  getCaseInfoByCaseId: SYS_URL1 + 'caseInfo/getCaseInfoByCaseId',
  queryBillStatisticsByCaseId: SYS_URL1 + 'Bill/queryBillStatisticsByCaseId',

  //项目管理
  createProject: SYS_URL11 + 'project/createProject',
  queryFolderViewData: SYS_URL11 + 'project/queryFolderViewData',
  queryFolderViewTasks: SYS_URL11 + 'project/queryFolderViewTasks',
  queryFolderViewSubtasks: SYS_URL11 + 'project/queryFolderViewSubtasks',
  queryFolderViewSubtasksLevel4: SYS_URL11 + 'project/queryFolderViewSubtasksLevel4',
  queryProjectDetail: SYS_URL11 + 'project/queryProjectDetail',
  updateProject: SYS_URL11 + 'project/updateProject',
  deleteProjectUrl: SYS_URL11 + 'project/deleteProject',
  queryActivityLog: SYS_URL11 + 'audit/queryActivityLog',
  queryChangeHistory: SYS_URL11 + 'audit/queryChangeHistory',
  createTaskUrl: SYS_URL11 + 'task/createTask',
  updateTaskUrl: SYS_URL11 + 'task/updateTask',
  deleteTaskUrl: SYS_URL11 + 'task/deleteTask',
  queryTaskDetail: SYS_URL11 + 'task/queryTaskDetail',
  getAllTasklist: SYS_URL11 + 'project/globalSearch',
  //子事项
  createSubtask: SYS_URL11 + 'subtask/createSubtask',
  updateSubtask: SYS_URL11 + 'subtask/updateSubtask',
  deleteSubtask: SYS_URL11 + 'subtask/deleteSubtask',
  querySubtaskDetail: SYS_URL11 + 'subtask/querySubtaskDetail',
  //引用
  queryRelatedCases: SYS_URL11 + 'task/case/query',
  addRelatedCase: SYS_URL11 + 'task/case/add',
  removeRelatedCase: SYS_URL11 + 'task/case/batchRemove',
  queryRelatedTasks: SYS_URL11 + 'task/reference/query',
  addRelatedTask: SYS_URL11 + 'task/reference/add',
  removeRelatedTask: SYS_URL11 + 'task/reference/remove',
  deleteMaterialUrl: SYS_URL11 + 'material/deleteMaterial',
  //附件
  createPrjMaterialUrl:`${window.location.origin}/ip_project/interface/material/createMaterial`,
  downloadMaterial: SYS_URL11 + 'material/downloadMaterial',
  viewMaterial: SYS_URL11 + 'material/viewMaterial',
  //备注
  addTaskNote: SYS_URL11 + 'task/note/addNote',
  updateTaskNote: SYS_URL11 + 'task/note/updateNote',
  deleteTaskNote: SYS_URL11 + 'task/note/deleteNote',
  queryTaskNoteList: SYS_URL11 + 'task/note/queryNoteList',
  addSubtaskNote: SYS_URL11 + 'subtask/note/addNote',
  updateSubtaskNote: SYS_URL11 + 'subtask/note/updateNote',
  deleteSubtaskNote: SYS_URL11 + 'subtask/note/deleteNote',
  querySubtaskNoteList: SYS_URL11 + 'subtask/note/queryNoteList',
  //统计
  queryProjectStatistics: SYS_URL11 + 'project/queryProjectStatistics',
  //检查权限
  checkEditPermission: SYS_URL11 + 'permission/checkEditPermission',
  //列表接口
  queryProjectListUrl: SYS_URL11 + 'project/queryProjectList',
  queryTaskListUrl: SYS_URL11 + 'task/queryTaskList',
  querySubtaskListUrl: SYS_URL11 + 'subtask/querySubtaskList',
  //查询用户角色
  queryUserRoleList: SYS_URL11 + 'project/queryUserRoleList',

  queryProjectList: SYS_URL11 + 'project/queryProjectsWithTaskSubtaskCount',
  queryTodoTaskByPrjId: SYS_URL11 + 'project/queryTasksSubtasksByProjects',
  queryMyTasksAsOwner: SYS_URL11 + 'project/queryMyTasksAsOwner',

  // 我的任务
  queryOwnerProjects: SYS_URL11 + 'project/queryProjectsWithMyTasksAsOwnerCount',
  queryOwnerTasksAndSubTasks: SYS_URL11 + 'project/queryMyTasksSubtasksByProject',
  queryOwnerSubTasks: SYS_URL11 + 'project/queryMySubtasksByTask',
  queryCalendars: SYS_URL1 + 'Outlook/queryCalendars',
  queryCalendarEvents: SYS_URL1 + 'Outlook/queryCalendarEvents',
}
module.exports = URL_Tem
