export const menuItems = [
  {
    id: 1,
    label: "menuitems.dashboards.text",
    icon: "bx-home-circle",
    link: "/",
    permissions: [496, 497],
  },
  {
    id: 2,
    label: "menuitems.mytask.text",
    icon: "bx-task",
    link: "/mytask",
  },
  {
    id: 3,
    label: "menuitems.item.text",
    icon: "bx-briefcase-alt-2",
    link: "/project",
  },
  {
    id: 4,
    label: "menuitems.customer.text",
    icon: "bx-user-pin",
    link: "/customer/customer-overview",
  },
  {
    id: 5,
    label: "menuitems.schedule.text",
    icon: "bx-calendar-alt",
    link: "/schedule",
  },
  {
    id: 6,
    label: "menuitems.case.text",
    icon: "bx-receipt",
    link: "/case/case-folders",
    permissions: [3],
  },

  // {
  //   id: 9,
  //   label: "menuitems.case.text",
  //   icon: "bx-receipt",
  //   permissions: [3],
  //   subItems: [
  //     {
  //       id: 11,
  //       label: "menuitems.case.list.trademark",
  //       link: "/case/case-trademark",
  //       parentId: 9,
  //       icon: "bx-detail",
  //     },
  //     {
  //       id: 14,
  //       label: "menuitems.case.list.patent",
  //       link: "/case/case-patent",
  //       parentId: 9,
  //       icon: "bx-detail",
  //     },
  //     {
  //       id: 12,
  //       label: "menuitems.case.list.litigation",
  //       link: "/case/case-litigation",
  //       parentId: 9,
  //       icon: "bx-detail",
  //     },
  //     {
  //       id: 13,
  //       label: "menuitems.case.list.protection",
  //       link: "/case/case-protection",
  //       parentId: 9,
  //       icon: "bx-detail",
  //     },
  //     {
  //       id: 15,
  //       label: "menuitems.case.list.domain",
  //       link: "/case/case-domain",
  //       parentId: 9,
  //       icon: "bx-detail",
  //     },
  //     {
  //       id: 16,
  //       label: "menuitems.case.list.copyright",
  //       link: "/case/case-copyright",
  //       parentId: 9,
  //       icon: "bx-detail",
  //     },
  //     {
  //       id: 17,
  //       label: "menuitems.case.list.nonlitigation",
  //       link: "/case/case-nonlitigation",
  //       parentId: 9,
  //       icon: "bx-detail",
  //     },
  //     {
  //       id: 18,
  //       label: "menuitems.case.list.allcases",
  //       link: "/case/case-allcases",
  //       parentId: 9,
  //       icon: "bx-detail",
  //     },
  //     {
  //       id: 18,
  //       label: "menuitems.case.list.allcases",
  //       link: "/case/case-allcases",
  //       parentId: 9,
  //       icon: "bx-detail",
  //     },
  //     {
  //       id: 10,
  //       label: "menuitems.case.list.filing",
  //       link: "/workbench/case/registration",
  //       parentId: 9,
  //       permissions: [18],
  //       icon: "bx-detail",
  //     },
  //   ],
  // },
  {
    id: 19,
    label: "menuitems.worktime.text",
    icon: "bx-calendar",
    link: "/workbench/worktime",
    permissions: [267],
  },
  // {
  //   id: 20,
  //   label: "menuitems.item.text",
  //   icon: "bx-briefcase-alt-2",
  //   subItems: [
  //     {
  //       id: 21,
  //       label: "menuitems.item.list.tasks",
  //       link: "/workbench/ResourceView/ResourceView1",
  //       parentId: 20,
  //       permissions: [267],
  //       icon: "bx-detail",
  //     },
  //     {
  //       id: 22,
  //       label: "menuitems.item.list.items",
  //       link: "/workbench/ResourceView/allProject",
  //       parentId: 20,
  //       permissions: [267],
  //       icon: "bx-detail",
  //     },
  //   ],
  // },
  {
    id: 23,
    label: "menuitems.process.text",
    icon: "bx-task",
    permissions: [19, 20],
    subItems: [
      {
        id: 24,
        label: "menuitems.process.list.submitofficial",
        link: "/workbench/technological_process/officialSubmission",
        parentId: 23,
        permissions: [19],
        icon: "bx bx-window-open",
      },
      {
        id: 25,
        label: "menuitems.process.list.notice",
        link: "/workbench/technological_process/officialCommunication",
        parentId: 23,
        permissions: [20],
        icon: "bx bx-message-dots",
      },
      {
        id: 26,
        label: "menuitems.process.list.writing",
        link: "/workbench/technological_process/trademarkWriting",
        parentId: 23,
        icon: "bx bx-edit-alt",
      },
    ],
  },
  {
    id: 27,
    label: "menuitems.knowledgebase.text",
    icon: "bx-chat",
    permissions: [251],
    subItems: [
      {
        id: 28,
        label: "menuitems.knowledgebase.list.knowledge_search",
        link: "/workbench/knowledgeBase/search",
        parentId: 27,
        permissions: [252],
        icon: "bx bx-book-open",
      },
      {
        id: 29,
        label: "menuitems.knowledgebase.list.data_statistics",
        link: "/workbench/knowledgeBase/statistics/caseTypeModel",
        parentId: 27,
        permissions: [253],
        icon: "bx bx-line-chart",
      },
      {
        id: 30,
        label: "menuitems.knowledgebase.list.knowledge_management",
        link: "/workbench/knowledgeBase/knowledge_management",
        parentId: 27,
        permissions: [254],
        icon: "bx bx-book-open",
      },
      {
        id: 31,
        label: "menuitems.knowledgebase.list.personal_articles",
        link: "/workbench/knowledgeBase/personal_articles",
        parentId: 27,
        permissions: [255],
        icon: "bx bxs-user",
      },
      {
        id: 32,
        label: "menuitems.knowledgebase.list.ai_knowledge_management",
        link: "/workbench/knowledgeBase/ai_knowledge_base",
        parentId: 27,
        permissions: [440],
        icon: "bx bx-bot",
      },
    ],
  },
  {
    id: 33,
    label: "menuitems.filemanager.text",
    icon: "bx-file",
    permissions: [5],
    subItems: [
      {
        id: 34,
        label: "menuitems.filemanager.list.file_management",
        link: "/workbench/material_management/material",
        parentId: 33,
        permissions: [24],
        icon: "bx bx-food-menu",
      },
      {
        id: 35,
        label: "menuitems.filemanager.list.internal_external_management",
        link: "/workbench/material_management/agencyMaterial",
        parentId: 33,
        permissions: [358],
        icon: "bx bx-detail",
      },
      {
        id: 36,
        label: "menuitems.filemanager.list.case_documents",
        link: "/workbench/material_management/caseMaterial",
        parentId: 33,
        permissions: [239],
        icon: "bx bx-book-content",
      },
      {
        id: 37,
        label: "menuitems.filemanager.list.archive_management",
        link: "/workbench/material_management/archiveMaterial",
        parentId: 33,
        icon: "bx bx-columns",
      },
    ],
  },
  {
    id: 38,
    label: "menuitems.data.text",
    icon: "bxs-bar-chart-alt-2",
    permissions: [6],
    subItems: [
      {
        id: 39,
        label: "menuitems.data.list.business_data",
        link: "/workbench/platformData/new_dashboard_index",
        parentId: 23,
        permissions: [361],
        icon: "bx bx-money",
      },
      {
        id: 40,
        label: "menuitems.data.list.human_resources",
        link: "/workbench/platformData/new_dashboard_hrm",
        parentId: 23,
        permissions: [299],
        icon: "bx bx-sitemap",
      },
      {
        id: 41,
        label: "menuitems.data.list.partner_weekly_report",
        link: "/workbench/platformData/partner_weekly_report",
        parentId: 23,
        permissions: [372],
        icon: "bx bx-calendar-plus",
      },
      {
        id: 42,
        label: "menuitems.data.list.law_firm_performance",
        link: "/workbench/platformData/lawyer_performance",
        parentId: 23,
        permissions: [384],
        icon: "bx bx-sort-up",
      },
      {
        id: 43,
        label: "menuitems.data.list.company_news",
        link: "/workbench/platformData/company_news",
        parentId: 23,
        permissions: [393],
        icon: "bx bx-news",
      },
      {
        id: 44,
        label: "menuitems.data.list.schedule_management",
        link: "/workbench/platformData/itinerary",
        parentId: 23,
        permissions: [405],
        icon: "bx bx-calendar",
      },
    ],
  },
  {
    id: 45,
    label: "menuitems.setting.text",
    icon: "bx-cog",
    permissions: [7],
    subItems: [
      {
        id: 46,
        label: "menuitems.setting.list.domestic_price_list",
        link: "/workbench/system_management/marked_management",
        parentId: 45,
        permissions: [27],
        icon: "bx bx-cart-alt",
      },
      {
        id: 47,
        label: "menuitems.setting.list.department_management",
        link: "/workbench/system_management/department_management",
        parentId: 45,
        permissions: [29],
        icon: "bx bx-sitemap",
      },
      {
        id: 48,
        label: "menuitems.setting.list.field_management",
        link: "/workbench/system_management/domain_management",
        parentId: 45,
        permissions: [196],
        icon: "bx bx-command",
      },
      {
        id: 49,
        label: "menuitems.setting.list.workgroup_management",
        link: "/workbench/system_management/workingGroup_management",
        parentId: 45,
        permissions: [30],
        icon: "bx bx-hive",
      },
      {
        id: 50,
        label: "menuitems.setting.list.employee_management",
        link: "/workbench/system_management/staff_management",
        parentId: 45,
        permissions: [31],
        icon: "bx bx-user-plus",
      },
      {
        id: 51,
        label: "menuitems.setting.list.role_management",
        link: "/workbench/system_management/role_management",
        parentId: 45,
        permissions: [32],
        icon: "bx bx-git-repo-forked",
      },
      {
        id: 52,
        label: "menuitems.setting.list.permission_management",
        link: "/workbench/system_management/permission_management/permission_Modular",
        parentId: 45,
        permissions: [33],
        icon: "bx bx-brightness",
      },
      {
        id: 53,
        label: "menuitems.setting.list.error_log",
        link: "/workbench/system_management/webLog",
        parentId: 45,
        permissions: [0],
        icon: "bx bx-show",
      },
      {
        id: 54,
        label: "menuitems.setting.list.template_approval",
        link: "/workbench/system_management/templateManagement",
        parentId: 45,
        permissions: [266],
        icon: "bx bx-selection",
      },
      {
        id: 55,
        label: "menuitems.setting.list.fee_approval_rules",
        link: "/workbench/system_management/feeRules",
        parentId: 45,
        permissions: [369],
        icon: "bx bx-add-to-queue",
      },
    ],
  },
  {
    id: 998,
    label: "menuitems.performanceAssessment.text",
    icon: "bx bx-bar-chart-alt-2",
    link: "/performance-assessment",
    permissions: [526],
  },
  {
    id: 56,
    label: "menuitems.hrm.text",
    icon: "bxs-user-detail",
    subItems: [
      {
        id: 58,
        label: "menuitems.hrm.list.personnel_management",
        link: "/hrm/staff-management",
        parentId: 56,
        permissions: [299],
        icon: "fas fa-address-book",
      },
      {
        id: 57,
        label: "menuitems.hrm.list.my_profile",
        link: "/workbench/hrm/my_profile",
        parentId: 56,
        icon: "bx bx-user",
      },
      {
        id: 435,
        label: "menuitems.hrm.list.my_attendance",
        link: "/hrm/my-attendance",
        parentId: 56,
        icon: "bx bx-time-five",
      },
      {
        id: 437,
        label: "menuitems.hrm.list.approval_center",
        link: "/hrm/my-attendance/approval-center",
        parentId: 56,
        icon: "bx bx-check-shield",
      },
      {
        id: 436,
        label: "假勤管理",
        link: "/hrm/attendance-management",
        parentId: 56,
        icon: "bx bx-calendar-event",
      },
      {
        id: 59,
        label: "menuitems.hrm.list.salary_management",
        link: "/workbench/hrm/payroll_management",
        parentId: 56,
        permissions: [427],
        icon: "mdi mdi-cash-usd-outline",
      },
      {
        id: 60,
        label: "menuitems.hrm.list.bonus_management",
        link: "/workbench/hrm/bonus_management",
        parentId: 56,
        permissions: [430],
        icon: "mdi mdi-account-cash",
      },
      {
        id: 61,
        label: "menuitems.hrm.list.payroll_statistics",
        link: "/workbench/hrm/salary_management",
        parentId: 56,
        permissions: [429],
        icon: "bx bx-dollar-circle",
      },
      {
        id: 62,
        label: "menuitems.hrm.list.approval_management",
        link: "/workbench/hrm/approval_management",
        parentId: 56,
        permissions: [446],
        icon: "bx bx-detail",
      },
    ],
  },
  {
    id: 63,
    label: "menuitems.finance.text",
    icon: "bx-wallet",
    permissions: [4],
    subItems: [
      {
        id: 68,
        label: "menuitems.finance.list.expenses",
        link: "/finance/finance-fee",
        permissions: [23],
        parentId: 63,
        icon: "bx bx-dollar-circle",
      },
      {
        id: 84,
        label: "menuitems.finance.list.overseas_bills",
        link: "/finance/bill-overseas",
        parentId: 63,
        permissions: [228],
        icon: "bx bx-file-find",
      },
      {
        id: 69,
        label: "menuitems.finance.list.expense_details",
        link: "/workbench/finance_fee_detail",
        parentId: 63,
        permissions: [333],
        icon: "bx bx-food-menu",
      },
      {
        id: 70,
        label: "menuitems.finance.list.receivables_management",
        link: "/workbench/finance_collect",
        parentId: 63,
        permissions: [302],
        icon: "bx bx-yen",
      },
      {
        id: 71,
        label: "menuitems.finance.list.financial_reconciliation",
        link: "/workbench/finance_statement",
        parentId: 63,
        permissions: [326],
        icon: "bx bx-check-square",
      },
      {
        id: 82,
        label: "menuitems.finance.list.official_fee_payment",
        link: "/workbench/finance_patent_fee",
        parentId: 63,
        permissions: [346],
        icon: "bx bx-money",
      },
      {
        id: 83,
        label: "menuitems.finance.list.overseas_quotations",
        link: "/workbench/finance_outside_price",
        parentId: 63,
        permissions: [291],
        icon: "bx bx-world",
      },
      {
        id: 85,
        label: "menuitems.finance.list.exchange_rate_settings",
        link: "/workbench/finance_exchange_rate",
        parentId: 63,
        permissions: [422],
        icon: "bx bx-dollar-circle",
      },
      {
        id: 72,
        label: "menuitems.finance.list.invoice_management.text",
        parentId: 63,
        icon: "bx bx-purchase-tag",
        subItems: [
          {
            id: 73,
            label:
              "menuitems.finance.list.invoice_management.list.invoice_opener",
            link: "/finance/invoice-management/invoice_opener",
            parentId: 72,
            permissions: [213],
            icon: "bx bx-duplicate",
          },
          {
            id: 74,
            label:
              "menuitems.finance.list.invoice_management.list.borrowed_invoices",
            link: "/workbench/finance_invoice/finance_invoice_borrow",
            parentId: 72,
            icon: "bx bx-left-arrow-circle",
          },
          {
            id: 75,
            label:
              "menuitems.finance.list.invoice_management.list.invoice_repository",
            link: "/workbench/finance_invoice/finance_invoice_library",
            parentId: 72,
            icon: "bx bx-box",
          },
        ],
      },
      {
        id: 64,
        label: "menuitems.finance.list.billing_management.text",
        parentId: 63,
        permissions: [22],
        icon: "bx bx-columns",
        subItems: [
          {
            id: 65,
            label: "menuitems.finance.list.billing_management.list.bills",
            link: "/finance/bill-management/bill",
            parentId: 64,
            permissions: [84],
            icon: "bx bx-calculator",
          },
          {
            id: 66,
            label:
              "menuitems.finance.list.billing_management.list.internal_bills",
            link: "/finance/bill-management/bill-internal",
            parentId: 64,
            permissions: [85],
            icon: "bx bx-paste",
          },
          {
            id: 67,
            label: "menuitems.finance.list.billing_management.list.drafts",
            link: "/workbench/finance_bill_manager/finance_traw_sheet",
            parentId: 64,
            permissions: [86],
            icon: "bx bx-detail",
          },
        ],
      },
      {
        id: 77,
        label: "menuitems.finance.list.report_center.text",
        parentId: 63,
        icon: "bx bx-folder-plus",
        subItems: [
          {
            id: 78,
            label: "menuitems.finance.list.report_center.list.reports",
            link: "/workbench/finance_report/finance_report_form",
            parentId: 77,
            icon: "bx bx-file",
          },
          {
            id: 79,
            label:
              "menuitems.finance.list.report_center.list.report_management",
            link: "/workbench/finance_report/finance_report_manage",
            parentId: 77,
            icon: "bx bx-detail",
          },
          {
            id: 80,
            label:
              "menuitems.finance.list.report_center.list.entity_management",
            link: "/workbench/finance_report/finance_report_company",
            parentId: 77,
            icon: "bx bx-data",
          },
          {
            id: 81,
            label:
              "menuitems.finance.list.report_center.list.account_management",
            link: "/workbench/finance_report/finance_report_account",
            parentId: 77,
            icon: "bx bx-credit-card",
          },
        ],
      },
    ],
  },
  // {
  //   id: 86,
  //   label: "menuitems.customer.text",
  //   icon: "bx-user-pin",
  //   permissions: [2],
  //   subItems: [
  //     // {
  //     //   id: 87,
  //     //   label: "menuitems.customer.list.customer_info",
  //     //   link: "/customer/customer-info",
  //     //   parentId: 86,
  //     //   permissions: [10],
  //     //   icon: "bx-detail",
  //     // },
  //     {
  //       id: 88,
  //       label: "menuitems.customer.list.business_opportunities",
  //       link: "/workbench/customer_business_opportunities",
  //       parentId: 86,
  //       permissions: [17],
  //       icon: "bx-detail",
  //     },
  //     {
  //       id: 89,
  //       label: "menuitems.customer.list.responsible_person",
  //       link: "/workbench/customer_commander",
  //       parentId: 86,
  //       permissions: [409],
  //       icon: "bx-detail",
  //     },
  //     {
  //       id: 90,
  //       label: "menuitems.customer.list.data_statistics",
  //       link: "/workbench/customer_statistics/common_solutions",
  //       parentId: 86,
  //       permissions: [411],
  //       icon: "bx-detail",
  //     },
  //     {
  //       id: 91,
  //       label: "menuitems.customer.list.customer_activities",
  //       link: "/workbench/customer_activity",
  //       parentId: 86,
  //       permissions: [16],
  //       icon: "bx-detail",
  //     },
  //     {
  //       id: 92,
  //       label: "menuitems.customer.list.market_efficiency",
  //       link: "/workbench/market_activity",
  //       parentId: 86,
  //       permissions: [414],
  //       icon: "bx-detail",
  //     },
  //     {
  //       id: 93,
  //       label: "menuitems.customer.list.customer_contacts",
  //       link: "/workbench/customer_other_contacts",
  //       parentId: 86,
  //       permissions: [15],
  //       icon: "bx-detail",
  //     },
  //     {
  //       id: 94,
  //       label: "menuitems.customer.list.official_agencies",
  //       link: "/workbench/customer_official_list",
  //       parentId: 86,
  //       permissions: [13],
  //       icon: "bx-detail",
  //     },
  //     {
  //       id: 95,
  //       label: "menuitems.customer.list.cooperation_resources",
  //       link: "/workbench/customer_cooperative_list",
  //       parentId: 86,
  //       permissions: [12],
  //       icon: "bx-detail",
  //     },
  //     {
  //       id: 96,
  //       label: "menuitems.customer.list.conflict_of_interest",
  //       link: "/workbench/customer_conflict_of_list",
  //       parentId: 86,
  //       permissions: [14],
  //       icon: "bx-detail",
  //     },
  //     {
  //       id: 97,
  //       label: "menuitems.customer.list.applicant",
  //       link: "/workbench/customer_applicant_list",
  //       parentId: 86,
  //       permissions: [11],
  //       icon: "bx-detail",
  //     },
  //     {
  //       id: 98,
  //       label: "menuitems.customer.list.group_customers",
  //       link: "/workbench/customer_groupcust_list",
  //       parentId: 86,
  //       permissions: [412],
  //       icon: "bx-detail",
  //     },
  //     {
  //       id: 98,
  //       label: "menuitems.customer.list.doormanage",
  //       link: "/workbench/customer_doormanage_list",
  //       parentId: 86,
  //       permissions: [438],
  //       icon: "bx-detail",
  //     },
  //   ],
  // },
  {
    id: 100,
    label: "menuitems.release.list.releaselist",
    icon: "bx-help-circle",
    link: "/releaseslist",
    permissions: [498],
  },
  {
    id: 300,
    label: "menuitems.bussiness_trip.text",
    icon: "bx bx-briefcase",
    link: "/businesstrip-management",
    // permissions: [490],
  },
  {
    id: 301,
    label: "menuitems.management.list.contract-management",
    icon: "bx bx-paste",
    link: "/management/contract-management",
  },
];
