export const seniorLayouts = {
  lg: [
    {
      x: 0,
      y: 0,
      w: 12,
      h: 6,
      minH: 6,
      minW: 12,
      wbmId: 6661,
      i: 6661,
      cpn: "MatterContainer",
      name:"待办任务卡片",
      moduleType: "lg"
    },
    {
      x: 0,
      y: 6,
      w: 12,
      h: 1,
      minH: 1,
      minW: 12,
      wbmId: 1,
      i: 1,
      delable:0,
      cpn: "ManagementTitle",
      moduleType: "lg"
    },
    {
      x: 0,
      y: 7,
      w: 3,
      h: 3,
      minH: 3,
      minW: 3,
      wbmId: 2,
      i: 2,
      cpn: "TotalRevenue",
      moduleType: "lg"
    },
    {
      x: 3,
      y: 7,
      w: 3,
      h: 3,
      minH: 3,
      minW: 3,
      wbmId: 3,
      i: 3,
      cpn: "TotalFee",
      moduleType: "lg"
    },
    {
      x: 6,
      y: 7,
      w: 3,
      h: 3,
      minH: 3,
      minW: 3,
      wbmId: 4,
      i: 4,
      cpn: "TotalProfit",
      moduleType: "lg"
    },
    {
      x: 9,
      y: 7,
      w: 3,
      h: 3,
      minH: 3,
      minW: 3,
      wbmId: 5,
      i: 5,
      cpn: "TotalGrossProfit",
      moduleType: "lg"
    },
    {
      x: 0,
      y: 10,
      w: 6,
      h: 8,
      minH: 6,
      minW: 6,
      wbmId: 605,
      i: 605,
      panelId: 605,
      isChart: 1,
      name: "收支余",
      moduleType: "lg"
    },
    {
      x: 6,
      y: 10,
      w: 6,
      h: 8,
      minH: 6,
      minW: 6,
      wbmId: 4021,
      i: 4021,
      panelId: 4021,
      isChart: 1,
      name: "领域账单收入占比",
      moduleType: "lg"
    },
    {
      x: 0,
      y: 18,
      w: 6,
      h: 8,
      minH: 6,
      minW: 6,
      wbmId: 4023,
      i: 4023,
      panelId: 4023,
      isChart: 1,
      name: "部门账单收入",
      moduleType: "lg"
    },
    {
      x: 6,
      y: 18,
      w: 6,
      h: 8,
      minH: 6,
      minW: 6,
      wbmId: 4024,
      i: 4024,
      panelId: 4024,
      isChart: 1,
      name: "各项支出占比",
      moduleType: "lg"
    },
    {
      x: 0,
      y: 26,
      w: 12,
      h: 1,
      minH: 1,
      minW: 12,
      wbmId: 4535,
      i: 4535,
      cpn: "PerformanceTitle",
      delable:0,
      moduleType: "lg"
    },
    {
      x: 0,
      y: 27,
      w: 6,
      h: 8,
      minH: 6,
      minW: 6,
      wbmId: 4042,
      i: 4042,
      isChart: 1,
      panelId: 4042,
      name: "合伙人业绩",
      moduleType: "lg"
    },
    {
      x: 6,
      y: 27,
      w: 6,
      h: 8,
      minH: 6,
      minW: 6,
      wbmId: 4041,
      i: 4041,
      isChart: 1,
      panelId: 4041,
      name: "律师绩效",
      moduleType: "lg"
    },
    {
      x: 0,
      y: 35,
      w: 6,
      h: 8,
      minH: 6,
      minW: 6,
      wbmId: 13122,
      i: 13122,
      isChart: 1,
      panelId: 131,
      name: "工时记录",
      moduleType: "lg"
    },
    {
      x: 6,
      y: 35,
      w: 6,
      h: 8,
      minH: 6,
      minW: 6,
      wbmId: 4044,
      i: 4044,
      isChart: 1,
      panelId: 4044,
      name: "客户负责人统计",
      moduleType: "lg"
    },
    {
      x: 0,
      y: 43,
      w: 12,
      h: 1,
      minH: 1,
      minW: 12,
      wbmId: 2322,
      i: 2322,
      cpn: "HrmTitle",
      delable:0,
      moduleType: "lg"
    },
    {
      x: 0,
      y: 44,
      w: 3,
      h: 3,
      minH: 3,
      minW: 3,
      wbmId: 6,
      i: 6,
      cpn: "EmployeesTotal",
      moduleType: "lg"
    },
    {
      x: 3,
      y: 44,
      w: 3,
      h: 3,
      minH: 3,
      minW: 3,
      wbmId: 7,
      i: 7,
      cpn: "EmployeesTurnover",
      moduleType: "lg"
    },
    {
      x: 6,
      y: 44,
      w: 3,
      h: 3,
      minH: 3,
      minW: 3,
      wbmId: 8,
      i: 8,
      cpn: "EmployeesAverageyear",
      moduleType: "lg"
    },
    {
      x: 9,
      y: 44,
      w: 3,
      h: 3,
      minH: 3,
      minW: 3,
      wbmId: 9,
      i: 9,
      cpn: "EmployeesAveragewages",
      moduleType: "lg"
    },
    {
      x: 0,
      y: 47,
      w: 6,
      h: 8,
      minH: 6,
      minW: 6,
      wbmId: 908,
      i: 908,
      isChart: 1,
      panelId: 908,
      name: "人员结构分布",
      moduleType: "lg"
    },
    {
      x: 6,
      y: 47,
      w: 6,
      h: 8,
      minH: 6,
      minW: 6,
      wbmId: 4036,
      i: 4036,
      isChart: 1,
      panelId: 4036,
      name: "执证情况分布",
      moduleType: "lg"
    },
    {
      x: 0,
      y: 55,
      w: 12,
      h: 1,
      minH: 1,
      minW: 12,
      wbmId: 103123,
      i: 1012312,
      cpn: "CustomerTitle",
      delable:0,
      moduleType: "lg"
    },
    {
      x: 0,
      y: 56,
      w: 3,
      h: 3,
      minH: 3,
      minW: 3,
      wbmId: 10,
      i: 10,
      cpn: "CustomerImportant",
      moduleType: "lg"
    },
    {
      x: 3,
      y: 56,
      w: 1.5,
      h: 3,
      minH: 3,
      minW: 1,
      wbmId: 11,
      i: 11,
      cpn: "CustomerNew",
      moduleType: "lg"
    },
    {
      x: 4.5,
      y: 56,
      w: 1.5,
      h: 3,
      minH: 3,
      minW: 1,
      wbmId: 12,
      i: 12,
      cpn: "CustomerCase",
      moduleType: "lg"
    },
    {
      x: 6,
      y: 56,
      w: 3,
      h: 3,
      minH: 3,
      minW: 3,
      wbmId: 1322,
      i: 1322,
      cpn: "CustomerPotential",
      moduleType: "lg"
    },
    {
      x: 9,
      y: 56,
      w: 3,
      h: 3,
      minH: 3,
      minW: 3,
      wbmId: 14,
      i: 14,
      cpn: "CustomerAlert",
      moduleType: "lg"
    },
    {
      x: 0,
      y: 59,
      w: 12,
      h: 8,
      minH: 6,
      minW: 12,
      wbmId: 15,
      i: 15,
      title: "客户列表",
      cpn: "CustomerList",
      moduleType: "lg"
    },
    {
      x: 0,
      y: 67,
      w: 12,
      h: 8,
      minH: 6,
      minW: 6,
      wbmId: 16,
      i: 16,
      title: "全球销售地图",
      cpn: "CustomerWorldMap",
      moduleType: "lg"
    },
    {
      x: 0,
      y: 59,
      w: 6,
      h: 8,
      minH: 6,
      minW: 6,
      wbmId: 4051,
      i: 4051,
      panelId: 4051,
      isChart: 1,
      name: "活跃客户国籍分布",
      moduleType: "lg"
    },
    {
      x: 6,
      y: 59,
      w: 6,
      h: 8,
      minH: 6,
      minW: 6,
      wbmId: 318,
      i: 318,
      panelId: 318,
      isChart: 1,
      name: "客户分案件类型占比",
      moduleType: "lg"
    },
    {
      x: 0,
      y: 67,
      w: 12,
      h: 1,
      minH: 1,
      minW: 12,
      wbmId: 2134,
      i: 214343,
      cpn: "BusinessDataTitle",
      delable:0,
      moduleType: "lg"
    },
    {
      x: 0,
      y: 78,
      w: 6,
      h: 8,
      minH: 6,
      minW: 6,
      wbmId: 214,
      i: 214,
      panelId: 214,
      isChart: 1,
      name: "部门案量",
      moduleType: "lg"
    },
    {
      x: 6,
      y: 78,
      w: 6,
      h: 8,
      minH: 6,
      minW: 6,
      wbmId: 4029,
      i: 4029,
      panelId: 4029,
      isChart: 1,
      name: "某领域各类型案量占比",
      moduleType: "lg"
    },
    {
      x: 0,
      y: 76,
      w: 6,
      h: 8,
      minH: 6,
      minW: 6,
      wbmId: 4030,
      i: 4030,
      panelId: 4030,
      isChart: 1,
      name: "权利领域案量占比",
      moduleType: "lg"
    },
    {
      x: 6,
      y: 76,
      w: 6,
      h: 8,
      minH: 6,
      minW: 6,
      wbmId: 201,
      i: 201,
      panelId: 201,
      isChart: 1,
      name: "按申请人国籍案量趋势统计",
      moduleType: "lg"
    },
    {
      x: 0,
      y: 84,
      w: 6,
      h: 10,
      minH: 6,
      minW: 4,
      wbmId: 234234,
      i: 54534,
      cpn: "MattersImportant",
      moduleType: "lg"
    },
    {
      x: 6,
      y: 84,
      w: 6,
      h: 10,
      minH: 6,
      minW: 4,
      wbmId: 234243434,
      i: 543453534,
      cpn: "CasesImportant",
      moduleType: "lg"
    },
  ],
  sm: [
    {
      x: 0,
      y: 0,
      w: 6,
      h: 12,
      minH: 12,
      minW: 6,
      wbmId: 6661,
      i: 6661,
      cpn: "MatterContainer",
      name:"待办任务卡片",
      moduleType: "sm"
    },
    {
      x: 0,
      y: 12,
      w: 6,
      h: 1,
      minH: 1,
      minW: 6,
      wbmId: 1,
      i: 1,
      cpn: "ManagementTitle",
      delable:0,
      moduleType: "sm"
    },
    {
      x: 0,
      y: 13,
      w: 3,
      h: 3,
      minH: 3,
      minW: 3,
      wbmId: 2,
      i: 2,
      cpn: "TotalRevenue",
      moduleType: "sm"
    },
    {
      x: 3,
      y: 13,
      w: 3,
      h: 3,
      minH: 3,
      minW: 3,
      wbmId: 3,
      i: 3,
      cpn: "TotalFee",
      moduleType: "sm"
    },
    {
      x: 0,
      y: 16,
      w: 3,
      h: 3,
      minH: 3,
      minW: 3,
      wbmId: 4,
      i: 4,
      cpn: "TotalProfit",
      moduleType: "sm"
    },
    {
      x: 3,
      y: 16,
      w: 3,
      h: 3,
      minH: 3,
      minW: 3,
      wbmId: 5,
      i: 5,
      cpn: "TotalGrossProfit",
      moduleType: "sm"
    },
    {
      x: 0,
      y: 19,
      w: 6,
      h: 8,
      minH: 6,
      minW: 6,
      wbmId: 605,
      i: 605,
      panelId: 605,
      isChart: 1,
      name: "收支余",
      moduleType: "sm"
    },
    {
      x: 0,
      y: 27,
      w: 6,
      h: 8,
      minH: 6,
      minW: 6,
      wbmId: 4021,
      i: 4021,
      panelId: 4021,
      isChart: 1,
      name: "领域账单收入占比",
      moduleType: "sm"
    },
    {
      x: 0,
      y: 35,
      w: 6,
      h: 8,
      minH: 6,
      minW: 6,
      wbmId: 4023,
      i: 4023,
      panelId: 4023,
      isChart: 1,
      name: "部门账单收入",
      moduleType: "sm"
    },
    {
      x: 0,
      y: 43,
      w: 6,
      h: 8,
      minH: 6,
      minW: 6,
      wbmId: 4024,
      i: 4024,
      panelId: 4024,
      isChart: 1,
      name: "各项支出占比",
      moduleType: "sm"
    },
    {
      x: 0,
      y: 51,
      w: 6,
      h: 1,
      minH: 1,
      minW: 6,
      wbmId: 4535,
      i: 4535,
      cpn: "PerformanceTitle",
      delable:0,
      moduleType: "sm"
    },
    {
      x: 0,
      y: 52,
      w: 6,
      h: 8,
      minH: 6,
      minW: 6,
      wbmId: 4042,
      i: 4042,
      isChart: 1,
      panelId: 4042,
      name: "合伙人业绩",
      moduleType: "sm"
    },
    {
      x: 0,
      y: 60,
      w: 6,
      h: 8,
      minH: 6,
      minW: 6,
      wbmId: 4041,
      i: 4041,
      isChart: 1,
      panelId: 4041,
      name: "律师绩效",
      moduleType: "sm"
    },
    {
      x: 0,
      y: 68,
      w: 6,
      h: 8,
      minH: 6,
      minW: 6,
      wbmId: 13122,
      i: 13122,
      isChart: 1,
      panelId: 131,
      name: "工时记录",
      moduleType: "sm"
    },
    {
      x: 0,
      y: 76,
      w: 6,
      h: 8,
      minH: 6,
      minW: 6,
      wbmId: 4044,
      i: 4044,
      isChart: 1,
      panelId: 4044,
      name: "客户负责人统计",
      moduleType: "sm"
    },
    {
      x: 0,
      y: 84,
      w: 6,
      h: 1,
      minH: 1,
      minW: 6,
      wbmId: 2322,
      i: 2322,
      cpn: "HrmTitle",
      delable:0,
      moduleType: "sm"
    },
    {
      x: 0,
      y: 85,
      w: 3,
      h: 3,
      minH: 3,
      minW: 3,
      wbmId: 6,
      i: 6,
      cpn: "EmployeesTotal",
      moduleType: "sm"
    },
    {
      x: 3,
      y: 85,
      w: 3,
      h: 3,
      minH: 3,
      minW: 3,
      wbmId: 7,
      i: 7,
      cpn: "EmployeesTurnover",
      moduleType: "sm"
    },
    {
      x: 0,
      y: 88,
      w: 3,
      h: 3,
      minH: 3,
      minW: 3,
      wbmId: 8,
      i: 8,
      cpn: "EmployeesAverageyear",
      moduleType: "sm"
    },
    {
      x: 3,
      y: 88,
      w: 3,
      h: 3,
      minH: 3,
      minW: 3,
      wbmId: 9,
      i: 9,
      cpn: "EmployeesAveragewages",
      moduleType: "sm"
    },
    {
      x: 0,
      y: 91,
      w: 6,
      h: 8,
      minH: 6,
      minW: 6,
      wbmId: 908,
      i: 908,
      isChart: 1,
      panelId: 908,
      name: "人员结构分布",
      moduleType: "sm"
    },
    {
      x: 0,
      y: 99,
      w: 6,
      h: 8,
      minH: 6,
      minW: 6,
      wbmId: 4036,
      i: 4036,
      isChart: 1,
      panelId: 4036,
      name: "执证情况分布",
      moduleType: "sm"
    },
    {
      x: 0,
      y: 107,
      w: 12,
      h: 1,
      minH: 1,
      minW: 12,
      wbmId: 103123,
      i: 1012312,
      cpn: "CustomerTitle",
      delable:0,
      moduleType: "sm"
    },
    {
      x: 0,
      y: 108,
      w: 3,
      h: 3,
      minH: 3,
      minW: 3,
      wbmId: 10,
      i: 10,
      cpn: "CustomerImportant",
      moduleType: "sm"
    },
    {
      x: 3,
      y: 108,
      w: 1.5,
      h: 3,
      minH: 3,
      minW: 1,
      wbmId: 11,
      i: 11,
      cpn: "CustomerNew",
      moduleType: "sm"
    },
    {
      x: 4.5,
      y: 108,
      w: 1.5,
      h: 3,
      minH: 3,
      minW: 1,
      wbmId: 12,
      i: 12,
      cpn: "CustomerCase",
      moduleType: "sm"
    },
    {
      x: 0,
      y: 111,
      w: 3,
      h: 3,
      minH: 3,
      minW: 3,
      wbmId: 1322,
      i: 1322,
      cpn: "CustomerPotential",
      moduleType: "sm"
    },
    {
      x: 3,
      y: 111,
      w: 3,
      h: 3,
      minH: 3,
      minW: 3,
      wbmId: 14,
      i: 14,
      cpn: "CustomerAlert",
      moduleType: "sm"
    },
    {
      x: 0,
      y: 114,
      w: 6,
      h: 8,
      minH: 6,
      minW: 6,
      wbmId: 4051,
      i: 4051,
      panelId: 4051,
      isChart: 1,
      name: "活跃客户国籍分布",
      moduleType: "sm"
    },
    {
      x: 0,
      y: 122,
      w: 6,
      h: 8,
      minH: 6,
      minW: 6,
      wbmId: 318,
      i: 318,
      panelId: 318,
      isChart: 1,
      name: "客户分案件类型占比",
      moduleType: "sm"
    },
    {
      x: 0,
      y: 130,
      w: 12,
      h: 1,
      minH: 1,
      minW: 12,
      wbmId: 2134,
      i: 214343,
      cpn: "BusinessDataTitle",
      delable:0,
      moduleType: "sm"
    },
    {
      x: 0,
      y: 131,
      w: 6,
      h: 8,
      minH: 6,
      minW: 6,
      wbmId: 214,
      i: 214,
      panelId: 214,
      isChart: 1,
      name: "部门案量",
      moduleType: "sm"
    },
    {
      x: 0,
      y: 139,
      w: 6,
      h: 8,
      minH: 6,
      minW: 6,
      wbmId: 4029,
      i: 4029,
      panelId: 4029,
      isChart: 1,
      name: "某领域各类型案量占比",
      moduleType: "sm"
    },
    {
      x: 0,
      y: 147,
      w: 6,
      h: 8,
      minH: 6,
      minW: 6,
      wbmId: 4030,
      i: 4030,
      panelId: 4030,
      isChart: 1,
      name: "权利领域案量占比",
      moduleType: "sm"
    },
    {
      x: 0,
      y: 155,
      w: 6,
      h: 8,
      minH: 6,
      minW: 6,
      wbmId: 201,
      i: 201,
      panelId: 201,
      isChart: 1,
      name: "按申请人国籍案量趋势统计",
      moduleType: "sm"
    },
  ],
};